### ISSUE TITLE
Global statistics

### ISSUE THREAD

**Issue by PowerKiKi** [Ecodev/newsletter#10]
Improve statistics to have a better global overview of all pages sent as newsletter.

Add a toggle button "current page/all pages" on top of newsletter list, or a list of pages, or a two level tree page->newsletter with current page selected by default?

Then be able to select several newsletter and see cumulative statistics. Beware, that may be a huge amount of data.

Also this Statistics page should always be available, independently of page currently selected in TYPO3 page tree, so we will probably rework what was done for #38572 to enable/disable tabs when appropriate (with a possible tooltip to explain the situation in addition to message in Status tab).

**Comment by marvin-martian** [comment]
> Also this Statistics page should always be available, independently of page currently selected
It would be nice to be able to configure this via a TSconfig so you could restrict it to pages in certain root paths. In a multi-domain setup you may only want the global overview statistics per domain by confining the pages shown by root path it would allow this. Or to be able to only allow certain BE users to see a particular segment of global overviews.

**Comment by PowerKiKi** [comment]
> confining the pages shown by root path

That sounds like a good compromise. Keep it simple for single domain install, while giving a bit of flexibility for multi-domains install. I'd go for that.
