### ISSUE TITLE
UX improvement: Add a href to the Newsletter URL in BE status tab

### ISSUE THREAD

**Issue by githubrsys** [Ecodev/newsletter#101]
The FE link in Status TAB should be a clickable link with target="_blank" 

That way it is not neccessary to copy and paste the url to get to the fe-view of the newsletter.

cheers

**Comment by PowerKiKi** [comment]
You're absolutely right, and I'd gladly accept a PR to do that. AFAIK I couldn't find a way to do that via ExtJS...

**Comment by githubrsys** [comment]
Can't this be just drop in \Ecodev\Newsletter\Utility\Validator ?

around line 100

````
$infos = array(sprintf($this->lang->getLL('validation_content_url'), '<a target="_blank" href="'.$url.'">'.$url.'</a>'));
````

**Comment by PowerKiKi** [comment]
As a matter of fact, yes it can. I guess I didn't try that hard back then... thanks for the suggestion :)
