### ISSUE TITLE
Suggestion: Background-Image Replacement

### ISSUE THREAD

**Issue by kludikovsky** [Ecodev/newsletter#102]
When creating Newsletters from pages, especially when using them based on Bootstrap background are difficult to eliminiate. Especially when the page should also bei accessible from the web.

I therefore suggest to remove the background-images statement and issue a warning, instead of just checking for them and issuing an error.

TODO: (locally done an works)
In **Validator.php** at line 172ff the following change need to be done.
```
         // Images in CSS
        if (preg_replace('|background-image: url\([^\)]+\)|','', $content) || preg_match('|list-style-image: url\([^\)]+\)|','', $content)) {
            $warnings[] = $this->lang->getLL('validation_mail_contains_css_images');
        }
```

There might also be an option to switch between both versions with a option setting.

**Comment by PowerKiKi** [comment]
Would you have a specific example of what you use in Bootstrap, that you would not want in an email, but would like to have on the browser versions ?

At first glance, I'd rather make only the minimal changes to content, to avoid confusing editors. So I'd tend to reject this idea as "out of scope", but maybe you (and others) can convince me.

**Comment by kludikovsky** [comment]
Quite simple.
To have a background image I use a background-image tag in CSS.
If I have a page now for the newsletter, that's in there. In addition there are a lot of `background-image: none;` tag as well, to reset whatsoever other tags.
All of those generate an error and prohibt the newsletter to be sent. This would require that I have to make a separate .css-file for the newsletter, but this is quite a job if I use the bootstrap_package.
With my proposal the background-image-tags just got replaced.

Just a statement to the *making changes to content*: I don't mean here content, but the included cc-files.
An there is a warning anyhow.

**Comment by githubrsys** [comment]
I'm with @PowerKiKi . This is out of scope as this is a template task. You have to face the truth that Newsletters do not have anything in common with actual FE Development. You really need a new Template for newsletters. 

Either from scratch or take a templating System for that. Like this http://zurb.com/playground/projects/responsive-email-templates/newsletter.html

So in fact: Bootstrap is not for Newsletters at all :-) 

Other way round asked: did you ask the bootstrap package people to provide a newsletter template?

**Comment by kludikovsky** [comment]
Yeah I'll see and agree.

What I need to find is a proper rendering TS for a newsletter.
Possibly I can use one from some 'old' versions where rendering was done using tables.

**Comment by PowerKiKi** [comment]
While I understand it is not the answer you wanted, I'll close this as WONTFIX, because out of scope. Unfortunately we have to deal with those annoying limitations ourselves.

**Comment by kludikovsky** [comment]
Agreed to close.
Here jsut for others in a similar situation.
I also tried the start template (extension start) but will finally end up with creating the mails in Mailchimp and copy the resulting HTML into a HTML-Contentelement.

Just to answer this question in advance: 
Q: Why not directly MailChimp? 
A: Those are sent from the MC domains, so this might result that the mails are running into SPAM if the user has got mails from other org's with which he is not happy with.

**Comment by githubrsys** [comment]
@PowerKiKi 

Perhaps it is not the most bad idea to put & deliver a standard newsletter template as kickstart for the folks. Either based on a mc or based on a foundation template as I mentioned above.

**Comment by carodb** [comment]
Hey guys,
I was thinking the same as @kludikovsky. Couldn't there at least be an option that you've acknowledged it is considered as a "not the best idea"-option but skipped anyways? I don't think having background-images in your CSS should prevent the newsletter from being sent at all.

Cheers!

**Comment by PowerKiKi** [comment]
@carodb In most cases missing background images would severely alter the appearance of the content. This is very likely to be an undesired effect and should be prevented at all cost.

A real solution to this problem would be to integrate some sort of engine to convert modern HTML/CSS to "email" HTML/CSS, see #6 for a discussion about that.
