### ISSUE TITLE
Show loading progress of newsletter status

### ISSUE THREAD

**Issue by kludikovsky** [Ecodev/newsletter#103]
In the backend when I select the newsletter module and the page with the newsletter, I get the Status page.
But the status page is empty. 
There is no indication that something is going on ('running circle', etc.) 
After some time the status is shown.

This is just a minor issue, but disturbs sometime, as one might think there is nothing, changing to another page missing the page.

So, if there is some time to  improve this would be a nice to have.

**Comment by PowerKiKi** [comment]
100% agree on that. Would gladly accept a PR for that.
