### ISSUE TITLE
various bug under t3 v.7.6

### ISSUE THREAD

**Issue by gilas1959** [Ecodev/newsletter#106]
Hi I'm looking for a newsletter +ext to run under typo3 7.6, but unfortuntely I can't find any valid plugin.

Newsletter +ext displays some strange behaviours:

* status page is always blank

* after selected a group well configured (test group via SQL) the test button doesn't works; pressing it do not happens nothing

* always as test sending attempt: I can see the email and the two links (html|plain) pressing one or the other apperas always this error (with a different code each time):
Oops, an error occurred! Code: 20160128123145674bf919

* tried to keep DEBUG flag set, via INSTALLER, nothing to do: the LOG via BE displays no errors...

* if I try to define a news usergroup the record is saved and there is no way to edit the box to add the group or user

* the test made was made using SQL to fetch an user from my BE

Substantially I think that there is severe errors (but I can't inspect because there is no output) and that the plugin is unusable with T3 7.6 - PHP 5.5 - MYSQL 5.5
? thank you for your help

**Comment by PowerKiKi** [comment]
Newsletter 2.6.0 is tested with TYPO3 7.6.0 and should work. First of all the status page should never be blank. That's your first clue that something is wrong and it should be fixed first before doing anything else. I'd suggest configuring `basic.fetch_path` in the Extension Manager.

On a side note if you successfully selected DEBUG preset for your TYPO3 install, then you should definitely get something somewhere, maybe in TYPO3 logs, or your webserver log, or maybe syslog.

**Comment by gilas1959** [comment]
Hi as I'm under urgency, I have installed direct_mail,
howevere your newsletter is very good and I appreciate it in the past.
Over new installation I will try newsletter +ext keeping valid your answer and check if all is OK.
thank you

**Comment by PowerKiKi** [comment]
Closing for now. Reopen when you have more details.
