### ISSUE TITLE
newsletter and bootstrap starter package

### ISSUE THREAD

**Issue by kludikovsky** [Ecodev/newsletter#107]
_This is not a bug:_

I am unable to get the newsletter as an email which is properly formatted in the email clients.

I understand that I can use any page as nesletter and this works.

 But the issue is that email clients lack the capability to properly display CSS-styled content, a reformatting need to be done to a table-styled content. At least this is my understanding. So either  table styled templtes need to be used, or some other magic restyling need to be done.

Can you guide us the right way to get to a reasonably formatted newsletter.

Thx.

**Comment by PowerKiKi** [comment]
Yes, you should most likely use an entirely different layout for Newsletter. And it sucks.

Check this reference: https://www.campaignmonitor.com/css/
Also read this entire discussion: #6
