### ISSUE TITLE
Unsubscribe redirection

### ISSUE THREAD

**Issue by thombeck** [Ecodev/newsletter#112]
Hi.
The redirection after unsubscribing doesn't work.
I think the value of module.tx_newsletter.config.unsubscribe_redirect is not taken into account in frontend.
May be due to$beConfManager ? (tools.php line 53) ?

Furthermore, in emailcontroller.php line 256 you have $uri = $uriBuilder->build();
This should not be $redirect = $uriBuilder->build(); ?

Regards

**Comment by PowerKiKi** [comment]
It seems you are right. Unfortunately I won't have much time to work on that until this summer. If you do have time, you could submit a PR and I will merge it. It would be great if you could cover that with functional tests.
