### ISSUE TITLE
Add List-Unsubscribe header

### ISSUE THREAD

**Issue by githubrsys** [Ecodev/newsletter#114]
For better spam scoring it is helpful to have a List-Unsubscribe header.

See solution here:
http://stackoverflow.com/questions/4365850/list-unsubscribe-in-e-mail-header-how-to

Unfortunately it only works perfect with a mailto: URL . So there would be a bit more work neccessary

**Comment by PowerKiKi** [comment]
Great idea. Planning to automate that in next release if a bounce account is available.
