### ISSUE TITLE
Feature : confirm unsubscribe

### ISSUE THREAD

**Issue by thombeck** [Ecodev/newsletter#115]
Hi
It would be nice if the user have to confirm the deregistration after clicking the unsubscribe link

**Comment by PowerKiKi** [comment]
I strongly believe that unsubscribing should be as simple as a single click. I think it also correspond to best practices. Thus I won't implement that and I won't accept a PR either.

But you are still free to implement an alternative workflow. It should be easy to build a custom link to your custom page that look and behave exactly as you want.
