### ISSUE TITLE
Permalink for newsletter

### ISSUE THREAD

**Issue by Oktopuce** [Ecodev/newsletter#116]
Hi,
Is there a way to have permalink for newsletter so that when a subscriber wants to see the inline version of the newsletter received by mail he can see the right version and not the most recent version if it have changed since he received the previous one.
Thanks,
Florian

**Comment by PowerKiKi** [comment]
Mentioned in the doc https://docs.typo3.org/typo3cms/extensions/newsletter/User/Index.html#simple-substitutions:

> In addition, the extension ‘Newsletter’ provide two built-in markers:
> 
> * `###newsletter_view_url###` URL to view the newsletter in a browser
> * `###newsletter_unsubscribe_url###` URL to unsubscribe from the newsletter (will register a bounce with type NEWSLETTER_UNSUBSCRIBE)

**Comment by PowerKiKi** [comment]
oh, but if you mean that you changed the page content in between, then no, there is no way.

**Comment by Oktopuce** [comment]
This is what I meant !
