### ISSUE TITLE
PHP Parse error Cronjob sending newsletter

### ISSUE THREAD

**Issue by Effectivewebdesign** [Ecodev/newsletter#118]
I have a problem to sending newsletters with the cronjob scheduler. I am using Typo3 6.2.25 wit ha PHP version 5.6. I have also tried to use a lower PHP version (5.4 as lowest selectable) but i get the same error message. I don not know if this is a problem of Newsletter or that i have to submit a ticket for the scheduler extension. I hope someone has a solution for this issue. 

Message title: (Where xxxxx is a path of the website) 
Cron /usr/local/cpanel/3rdparty/bin/php  /xxxxx/xxxxx/public_html/typo3/cli_dispatch.phpsh scheduler

Message content:
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /xxxxx/xxxxx/public_html/typo3temp/Cache/Code/cache_core/ext_tables_44f65227b128082569bdf47d04090bb097b504c3.php on line 3417

**Comment by PowerKiKi** [comment]
What's the content of `typo3temp/Cache/Code/cache_core/ext_tables_44f65227b128082569bdf47d04090bb097b504c3.php` line 3417 and around ?

I'd bet if you clear caches and/or delete that temp file, the problem should disappear.

**Comment by Effectivewebdesign** [comment]
Hi Adrian,

Thank you for the reply. After deleting the cached file i got another issue with the schedule task of the newsletter.
The issue was due to the extension pluploadfe which caused the problem.

After deinstallation of the file the problem was solved.

Thank you for the solution.
