### ISSUE TITLE
Switch to Version 3.0.0 corrupts html entities

### ISSUE THREAD

**Issue by githubrsys** [Ecodev/newsletter#120]
Hi,

I just updated the extension with DB Skript update. Went flawless. Cheers for that. But all htmlentities are broken since then. 

### New Code in sent newsletter (broken)
`und =?utf-8?Q?Ehevertr=C3=A4ge?=`
`=09=09 Wenn Sie den Newsletter nicht lesen k=C3=B6nnen=`

### Old Code in sent newsletter (not broken)
`und und =?utf-8?Q?Ehevertr=C3=83=C2=A4ge?=`
`=09=09 Wenn Sie den Newsletter nicht lesen k=C3=83==C2=B6nnen`

### Code in Frontend rendered page
`Wenn Sie den Newsletter nicht lesen können`

Page itself is in UTF8 of course and in the sent newsletter code the header has a utf8 
`--_=_swift_v4_1467971347_fc359dde2d0c4a207e4e69cb76e7fb4f_=_
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable`
`--_=_swift_v4_1467971347_398c3e0e7ba3bffba9f17a9cf9f498e5_=_
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable`

### php Version
`/usr/local/bin/php56/php -v
PHP 5.6.23 (cli) (built: Jul  8 2016 12:36:53) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v5.0.23, Copyright (c) 2002-2016, by ionCube Ltd.
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies`

**Comment by githubrsys** [comment]
I also tried switching from Lynx to Builtin and vice versa, but without success.

If I disable the Converters at all by removing them from the built URI, the code looks like this:
`wenn Sie den Newsletter nicht lesen k&Atilde;&para;nnen`

**Comment by githubrsys** [comment]
Switching back the Version to 2.60 Rendering works perfect. But in the end the DB is already altered.

**Comment by PowerKiKi** [comment]
I am pretty sure that it's the newly introduced `Ecodev\Newsletter\Utility\Validator::infoImageAlt()`. Specifically the `DomDocument` usage. However I am not quite sure yet how to solve this issue. Please let me know if you find how to.

Also you should be able to migrate from 2.6 to 3.0 back and forth without too much trouble, as long as you re-update the DB each time you migrate to 3.0 (the DB migration is only addition, so it won't break the 2.6 release).

**Comment by githubrsys** [comment]
#121 PR added

**Comment by PowerKiKi** [comment]
Solved in [3.0.1](https://github.com/Ecodev/newsletter/releases/tag/3.0.1)
