### ISSUE TITLE
Problem with redirect on unsubscribe

### ISSUE THREAD

**Issue by tbeaurin** [Ecodev/newsletter#122]
Hello,
In the new version of your extension, (3.0.1) I can't redirect the user on unsubscribe. I still have the Unsubscribed ***@***.com successfully.
It was working fine with your last bugfix in 2.6.1. Also I still have encoding problem with utf8.
Thanks (and sorry for my bad english)

**Comment by PowerKiKi** [comment]
What happened on unsubscribe ? do you get any kind of error ?

For UTF-8, what is the original content of the newsletter ? and what do you see in final email ?

Also what TYPO3 and PHP version ?

**Comment by tbeaurin** [comment]
On unsubscribe, I have the message "correctly unsubscrive", but i configure
in typoscript to be redirect on a page.
For the UTF-8, the original content has characters like é or è who are in
the final email like Ã©tÃ©.

I am on TYPO3 7.6.9 and PHP 5.6.22

2016-07-12 12:47 GMT+02:00 Adrien Crivelli <notifications@github.com>:

> What happened on unsubscribe ? do you get any kind of error ?
>
> For UTF-8, what is the original content of the newsletter ? and what do
> you see in final email ?
>
> Also what TYPO3 and PHP version ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Ecodev/newsletter/issues/122#issuecomment-232004710>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATeKBR-WZkxEmOpwqsDnrsV04Idx0MVuks5qU3C-gaJpZM4JKNY4>
> .
>



-- 
Tristan Beaurin

**Comment by PowerKiKi** [comment]
For redirect, please have a look at `newsletter/Classes/Controller/EmailController.php` around line 219-236. Could you see what is going there ? especially what is `$redirect` value at line 233 ?

For encoding, please open a new issue with the following details:
* URL of newsletter page if you can share it publicly or at least the source of the page with the original characters
* source of received email with wrongly encoded characters
* did you have issue with 2.6 ? and 3.0.0 ?

**Comment by tbeaurin** [comment]
Efter the debug, I can see that is was my mystake ; the typoscript constant
was not defined in regard of the setup.
All apologies.

2016-07-12 14:58 GMT+02:00 Adrien Crivelli <notifications@github.com>:

> For redirect, please have a look at
> newsletter/Classes/Controller/EmailController.php around line 219-236.
> Could you see what is going there ? especially what is $redirect value at
> line 233 ?
>
> For encoding, please open a new issue with the following details:
>
>    - URL of newsletter page if you can share it publicly or at least the
>    source of the page with the original characters
>    - source of received email with wrongly encoded characters
>    - did you have issue with 2.6 ? and 3.0.0 ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Ecodev/newsletter/issues/122#issuecomment-232039282>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATeKBQccFx9TcqVB4LW2vPB2VlAjxEHDks5qU4-EgaJpZM4JKNY4>
> .
>



-- 
Tristan Beaurin

**Comment by PowerKiKi** [comment]
Glad you could work it out.
