### ISSUE TITLE
TypoScript constants.ts

### ISSUE THREAD

**Issue by KillerDose** [Ecodev/newsletter#127]
Hey! I like your extension very much, but i've got one small hint for the documentation. The config for newsletters does not work in ts constants (module.tx_newsletter.config). For me it only works when i place it in my setup typoscript. I can even see it in typoscript object browser, but it has no effect since it is not placed in the setup.

**Comment by PowerKiKi** [comment]
@marvin-martian, since you implemented this feature in 1ede385b51391ff27cd16011bc402c469b79bc6e and documented it in 48fb271b1c0a2110ddb461fae3e339aa90d8fba0, can you confirm that it was the intended way to work ? only via setup, not constants ?

**Comment by marvin-martian** [comment]
Yes it is only in TS setup, not constants. You could modify a setup to use your constants if you want. The way the code works is that it looks for a TS setup, if it is not found it will fall back to the values set in the extension configuration. Sorry my documentation is not specific on that point.

**Comment by KillerDose** [comment]
That was just my point :) I only could not find where ext_conf_template.txt is finally included. The values in there are commented like constants but not wrapped by module.tx_newsletter, so it was not obvious for me how to use them. Thank you for your fast reaction!

**Comment by PowerKiKi** [comment]
@KillerDose would you like to create a PR to suggest an edit to the documentation ? I think you are the best person for that because you know exactly where/how you did not find the information you were looking for in the first place.

**Comment by KillerDose** [comment]
OK. I've never done that before, so it will take a while, i'm a noob at github. But i will do my best ;)

**Comment by PowerKiKi** [comment]
I am not sure where you would like to change things, but if it is in the docs, then you can simply navigate to the file and edit it directly in your browser. Maye [this one](https://github.com/Ecodev/newsletter/edit/master/Documentation/Configuration/Index.rst) ? Just be extra careful of what you edit (indentation and correct syntax). Then GitHub will prompt to create a PR with your changes. And we can review it together and improve on it if needed before merging.
