### ISSUE TITLE
Precedence:bulk in mailer.php

### ISSUE THREAD

**Issue by githubrsys** [Ecodev/newsletter#128]
## Summary

The "precedence: bulk"  in header set in mailer.php is a solution for giving hints to mailservers to avoid out of office messages. But unfortunately this invokes in outlook a "!! MASS-MESSAGE" introduction in the subject at the recieving party.
## Solution

Either make it optional in settings or remove it.

Cheers

**Comment by githubrsys** [comment]
## Update

removing the "precedence:bulk" only does not cure the phenomenom. But also removing the unsubscribe URL from the header part does. 

This is insane. Once put to get a better spam score it does behave in some mailclients (outlook2016, googlemail so far) like it is not wanted. 

So I think making these parts optionally or removing them entirely is the better choice.

Cheers and thanks for your work
David

**Comment by PowerKiKi** [comment]
What is the behavior observed in googlemail ?

**Comment by PowerKiKi** [comment]
Closing for lack of feedback
