### ISSUE TITLE
Implement feature Update Recipient list with csv

### ISSUE THREAD

**Issue by thombeck** [Ecodev/newsletter#130]
Hi,
It would be nice to be able to update a Recipient List with a csv file (like the recipients lists module of direct_mail )

**Comment by PowerKiKi** [comment]
There is 3 kind of support for CSV Recipient List, take your pick: https://docs.typo3.org/typo3cms/extensions/newsletter/Configuration/Index.html#recipient-lists

**Comment by thombeck** [comment]
The idea is to upload a SQL Recipient List from a csv so I can continue to use specific events (bounced email, unsubscribe).

**Comment by PowerKiKi** [comment]
IMHO this is out of scope. There are many ways to manage your data, but that's none of Newsletter business. I am reluctant to add that, because the next guy will ask to support MS Access. Maybe [wil_importcsv](https://typo3.org/extensions/repository/view/wil_importcsv) could do what you want ?

**Comment by thombeck** [comment]
I understand.
Thanks for your reponse, i'll try the extension
