### ISSUE TITLE
Task "Send Newsletter" gets stuck

### ISSUE THREAD

**Issue by siwa-pparzer** [Ecodev/newsletter#133]
Hi

My newsletter task gets stuck when executed - both on manually and cronjob.
Sometimes it succeeds sometimes not.

Probably this is caused by the server itself:
Our TYPO3 Instance is running in a docker container. Due to some configuration problems, you get a "bad gateway" return from the server, from time to time.
So I think the tasks wants to crawl the newsletter page but gets a 502 back and gets stuck.

Maybe implement a routine that tries a page 5 times before failing?

**Comment by PowerKiKi** [comment]
It seems it would best to fix the underlying stability issue the server has. If Newsletter has issues with it, chances are that somebody else also has issues with it.
