### ISSUE TITLE
sysext t3skin no longer exists in TYPO3 8 LTS

### ISSUE THREAD

**Issue by siwa-pparzer** [Ecodev/newsletter#137]
In the file `Classes/ViewHelpers/Be/ModuleContainerViewHelper.php - 48` you still use a css file of the sysext "t3skin" which is no longer existent.

Solution:
`$this->pageRenderer->addCssFile('sysext/t3skin/extjs/xtheme-t3skin.css');`
to
`$this->pageRenderer->addCssFile('sysext/core/Resources/Public/ExtJs/xtheme-t3skin.css');`

**Comment by PowerKiKi** [comment]
As you found out by now, Newsletter is [not tested and not compatible](https://travis-ci.org/Ecodev/newsletter) with TYPO3 8. So this is rather expected.

Unfortunately I don't have a specific timeline for a migration to TYPO3 8. It will eventually happen, but it could take a few more months. If you want to speed up that process, then you could contribute to the project by submitting PRs to drop support for all older TYPO3 and add support for TYPO3 8. This could be discussed in more details on Gitter.

**Comment by siwa-pparzer** [comment]
Oh sorry, thought it is compatible due to the `'typo3' => '6.2.0-8.99.99',` in the ext_emconf.php
I didn't test out all functions but it looks like this is the only main breaking error for now.
I'll test the extension in the next few weeks and provide more information and eventually start a TYPO3 8 PR.

**Comment by PowerKiKi** [comment]
That `'typo3' => '6.2.0-8.99.99',` was overly optimistic and was added in the very early stage of 8.0 IIRC. I never worked with TYPO3 8.7 yet, so it might be obscurely broken or working like a charm for all I know. Anyway I would be interested to hear your feedback on the matter...

**Comment by carodb** [comment]
Should be closed as fixed in: https://github.com/Ecodev/newsletter/commit/d91ea60449dec10543a6b7e25313a94c681267cc
