### ISSUE TITLE
Cannot view newsletter page with pageNotFound_handling

### ISSUE THREAD

**Issue by mbrodala** [Ecodev/newsletter#139]
If I try to view a newly created page planned for newsletter submission, all I get is a minimal page like this in the module content:

> Not Found
> 
> The requested URL /typo3/404/ was not found on this server.

The `404/` part comes from our `pageNotFound_handling` which is meant for frontend and working well:

```php
<?php
return [
    // ...
    'FE' => [
        // ...
        'pageNotFound_handling' => '404/',
        // ...
    ],
    // ...
];
```

As soon as as I uncomment that option, the module shows up fine.

Any idea what's wrong?

**Comment by PowerKiKi** [comment]
Do you mean `/typo3/index.php?M=web_NewsletterTxNewsletterM1&id=123` shows an error ? or is the actual newsletter content that show an error ?

**Comment by mbrodala** [comment]
As soon as I switch to the _System mails_ module and click on a newsletter page, I see the mentioned message. I see this in the network panel:

* `index.php?M=web_NewsletterTxNewsletterM1&moduleToken=<hash>&id=<newsletter-page-id>`, status 303
* `404/`, status 404

**Comment by PowerKiKi** [comment]
*System mails* is not part of Newsletter, I am not sure what you are referring to. You will most likely have to debug it by yourself. It might be an incompatibility with TYPO3 8 which is not yet supported. But you can still try to provide a screenshot with more details...

**Comment by mbrodala** [comment]
Ah, sorry, the module label was simply changed for a customer project, aside from that it's the default module without any change.

**Comment by mbrodala** [comment]
And we are using TYPO3 v7 here, Newsletter was just update to 3.0.2.

**Comment by mbrodala** [comment]
@PowerKiKi Please have another look at this.

**Comment by mbrodala** [comment]
@PowerKiKi Could you have another look at this? I'm also trying to debug this currently.

**Comment by PowerKiKi** [comment]
We do use `'pageNotFound_handling' => '/service/404-error/',` in our projects also, but without any problems. I am afraid I can't help you more, because I cannot replicate. You'll have to dig in the code to find out what's going on. I suggest removing all other extensions first, and see if it still happens...

**Comment by mbrodala** [comment]
If I change it to `/404/` I actually get our dedicated frontend 404 page, but no change. I'll have a look since currently the module is not usable for us. This did work fine on TYPO3 6.2 however.

**Comment by mbrodala** [comment]
It's really weird. I've now tracked it down like this:

1. `ModuleController::indexAction()`
1. `UriBuilder::buildFrontendUri()`
1. `UriBuilder::createUriBuilder()`
1. `TypoScriptFrontendController::fetch_the_id()`
1. `TypoScriptFrontendController::findDomainRecord()` and `PageRepository::getDomainStartPage()`
1. `TypoScriptFrontendController::getPageAndRootlineWithDomain()`

Since `typo3/index.php` is passed as `$path` to `PageRepository::getDomainStartPage()` TYPO3 is unable to find a domain record matching `example.org/typo3`.

I wonder what I am missing here...

**Comment by PowerKiKi** [comment]
Are you on 3.0.2 or 3.2.0 ? If not, update to latest 3.2.0 for https://github.com/Ecodev/newsletter/commit/177953e9ab611df2e5f14cf27c3bac2fa2614d45

**Comment by mbrodala** [comment]
Ah sorry, I'm in fact on 3.2.0, thus the very latest release.

**Comment by mbrodala** [comment]
OK, I found the actual issue: the page to process was disabled and for some unknown reason the usual _Hidden_ icon overlay was not shown, thus I didn't notice. Due to this the page obviously could not be accessed except from BE previews.

Now preparing the page an adding it to the queue did work just fine.

**Comment by mbrodala** [comment]
Here's a screenshot for reference:

![image](https://user-images.githubusercontent.com/5037116/27329397-b75983d6-55b5-11e7-9e29-d59da65da263.png)

(As you can see: no icon.)

**Comment by PowerKiKi** [comment]
Glad you coud find the issue and thanks for reporting back.
