### ISSUE TITLE
[BUG] Database analyzer

### ISSUE THREAD

**Issue by grimmcreative** [Ecodev/newsletter#141]
```
ALTER TABLE tx_newsletter_domain_model_newsletter CHANGE plain_converter `plain_converter` VARCHAR(255) DEFAULT 'Ecodev\\Newsletter\\Domain\\Model\\PlainConverter\\Builtin' NOT NULL 
Current value: plain_converter VARCHAR(255) DEFAULT 'Ecodev\Newsletter\Domain\Model\PlainConverter\Builtin' NOT NULL COLLATE utf8_unicode_ci
```

```
ALTER TABLE tx_newsletter_domain_model_recipientlist CHANGE type `type` VARCHAR(255) DEFAULT 'Ecodev\\Newsletter\\Domain\\Model\\RecipientList\\Sql' NOT NULL 
Current value: type VARCHAR(255) DEFAULT 'Ecodev\Newsletter\Domain\Model\RecipientList\Sql' NOT NULL COLLATE utf8_unicode_ci
```

**Comment by grimmcreative** [comment]
Just closing it? Why.
Issue still remains.

**Comment by PowerKiKi** [comment]
You didn't give any information about anything. There is nothing I can do.

**Comment by grimmcreative** [comment]
Information 1:
[BUG] Database analyzer
So its a BUG in the Database Analyzer inside Install Tool

That keeps up with Messages:
```
ALTER TABLE tx_newsletter_domain_model_recipientlist CHANGE type `type` VARCHAR(255) DEFAULT 'Ecodev\\Newsletter\\Domain\\Model\\RecipientList\\Sql' NOT NULL 
Current value: type VARCHAR(255) DEFAULT 'Ecodev\Newsletter\Domain\Model\RecipientList\Sql' NOT NULL COLLATE utf8_unicode_ci
```

and 

```
ALTER TABLE tx_newsletter_domain_model_recipientlist CHANGE type `type` VARCHAR(255) DEFAULT 'Ecodev\\Newsletter\\Domain\\Model\\RecipientList\\Sql' NOT NULL 
Current value: type VARCHAR(255) DEFAULT 'Ecodev\Newsletter\Domain\Model\RecipientList\Sql' NOT NULL COLLATE utf8_unicode_ci
```

What else information needed.

Issues occurs in Latest TYPO3 8.7.3
Database MySQL

**Comment by PowerKiKi** [comment]
You're most likely aware that the most useful bug reports include a description of what you do, what result is expected, what the actual result is and the versions of the most important pieces of software (here that would be at least Newsletter and TYPO3 and maybe PHP).

Those information are still missing.

**Comment by grimmcreative** [comment]
> First: i am inside the Github Instance of the TYPO3 Extension "Newsletter" - so why should i write "Hey its about the Newsletter extension of TYPO3"? Makes no sense.
> Second: Yes, i missed some Description and Values. 
> But this Bug is just related to the TYPO3 Version in use which i added in Second Description.
> PHP Version in use is of course 7xx because TYPO3 v8 is just running on Version 7.

**Environment:**

- TYPO3 8.7.3
- PHP 7.0.21
- MySQL 5.7.18
- Extension Newsletter "Latest TER Version" 3.2.0

**Bug:**

- Database Analyser is not able to ALTER TABLE

**_Information Message keeps alive:_**

```
ALTER TABLE tx_newsletter_domain_model_recipientlist CHANGE type `type` VARCHAR(255) DEFAULT 'Ecodev\\Newsletter\\Domain\\Model\\RecipientList\\Sql' NOT NULL 
Current value: type VARCHAR(255) DEFAULT 'Ecodev\Newsletter\Domain\Model\RecipientList\Sql' NOT NULL COLLATE utf8_unicode_ci
```

I hope you like it this way ;)

**Comment by grimmcreative** [comment]
https://github.com/Ecodev/newsletter/pull/142

**Comment by PowerKiKi** [comment]
A PR was submitted to dbal to fix this issue: https://github.com/doctrine/dbal/pull/2850
