### ISSUE TITLE
[BUG] Error for RecipientList when using Scheduler

### ISSUE THREAD

**Issue by carodb** [Ecodev/newsletter#150]
Hey there,

I'm getting the following error when trying to send the newsletter with Scheduler:

`Uncaught TYPO3 Exception: Argument 1 passed to Ecodev\Newsletter\Domain\Model\Newsletter::setRecipientList() must be an instance of Ecodev\Newsletter\Domain\Model\RecipientList, null given, called in /typo3conf/ext/newsletter/Classes/Domain/Model/Newsletter.php on line 669 | TypeError thrown in file /typo3conf/ext/newsletter/Classes/Domain/Model/Newsletter.php in line 632.`

I'm using TYPO3 v8 and newsletter 3.2.0. I know you haven't tested for v8 but maybe any suggestions/ideas? Help would be greatly appreciated! I'll try debugging as well.

Cheers!

**Comment by carodb** [comment]
Alright this seems a little odd: First the error prevented the sending of the mails but on the second execution of the scheduler it updated the status message and now my mail log is showing that some mails are being sent. So far no update on the count in the backend it just shows "0/x mails for this newsletter sent". I'll updated when the task is finished as there are a lot of mails being sent currently. In the BE I still get the error message as reported before.

**Comment by carodb** [comment]
Possible duplicate of: #61 ?

**Comment by PowerKiKi** [comment]
Do you have any RecipientList with a deleted or hidden flag to true ?

**Comment by carodb** [comment]
I did but I deleted the entries with the mentioned SQL in #61. Weird thing is that I only get the error in my live system and so far am not able to reproduce in my test environment. I have different PHP versions (7.1 in live, 7.0 in test). Didn't get the chance to check if that might be the problem but will try to test that as soon as I have the time.

**Comment by carodb** [comment]
Any chance on testing this @PowerKiKi ?

**Comment by PowerKiKi** [comment]
I unfortunately won't be able to invest much time into that in the next few weeks. Any debugging you could do would yourself and report here would help a lot.

**Comment by PowerKiKi** [comment]
Closing for lack of feedback. Feel free to re-open with more information
