### ISSUE TITLE
[BUG] After some editor changes in the backend, duplicate entry for key auth_code

### ISSUE THREAD

**Issue by socressor** [Ecodev/newsletter#154]
Hi there,

our customer has got the following error.
Many editors create contentelements and edit them on the self page where newsletter where send.
After some time they got the following messages after saving some contentelements:

![grafik](https://user-images.githubusercontent.com/11157552/36536611-e2ef1c74-17cd-11e8-8e50-06ed6c76204d.png)

Thank you

**Comment by PowerKiKi** [comment]
This case may happen if you duplicate records email record, via miscellaneous TYPO3 features. Those should not and cannot be duplicated. The solution is to avoid duplicating email records.

**Comment by socressor** [comment]
Ok, thanks.
