### ISSUE TITLE
remove t3skin relations

### ISSUE THREAD

**Issue by conpassione** [Ecodev/newsletter#156]
As stated in https://docs.typo3.org/typo3cms/extensions/core/7.6/Changelog/7.0/Breaking-61471-t3skinCssFilesMovedToLess.html all relations to t3skin should be removed.

For TYPO3 8LTS you schould change Line 48 in Classes/ViewHelpers/Be/ModuleContainerViewHelper.php

old: $this->pageRenderer->addCssFile('sysext/t3skin/extjs/xtheme-t3skin.css');
new: $this->pageRenderer->addCssFile('sysext/core/Resources/Public/ExtJs/xtheme-t3skin.css');

Please be aware that this is working only for TYPO3 8LTS, in TYPO3 9 ExtJs and t3skin will be removed!

Best Regards, Renzo

**Comment by PowerKiKi** [comment]
Thanks for the report. I always recommend installing from packagist, instead of TER, because it is easier to maintain and more reliable in my experience.

But I just checked Newsletter 3.3.1 as downloaded from TER and confirmed that it is also fixed and correctly contains the following lines:

```php
// From TYPO3 8.6.0 onward t3skin is located in core (see: https://forge.typo3.org/issues/79259).
if (version_compare(TYPO3_version, '8.6.0', '>=')) {
    $this->pageRenderer->addCssFile('sysext/core/Resources/Public/ExtJs/xtheme-t3skin.css');
} else {
    // Anything before 8.6.0 must still use the old t3skin EXT path.
    $this->pageRenderer->addCssFile('sysext/t3skin/extjs/xtheme-t3skin.css');
}
```
