### ISSUE TITLE
Setting Template Path + Statistic Issues

### ISSUE THREAD

**Issue by Asfga** [Ecodev/newsletter#157]
Hope I am right here with my problems, if not than sorry..
I tried a little bit around with the extension Newsletter in TYPO3 and it's almost everything how it should be. Two things I am not sure about or let's say I don't have any clue to get them working...

First thing is the statistic feature of this extension. It says that you can track opened emails and links. I found something in the typo3 backend to get the settings for it but don't know how to do it. There are two textfield (SQL to register an opened email, SQL to register a link clicked) and even a simple query like
```sql
UPDATE tx_newsletter_domain_model_email
SET open_time = 1
WHERE uid = 1
```
doesn't do anything in the database.

And the second problem is that I couldn't change the path of the root template. If I do it in my main setup.t3s file it won't work, direct typoscript in backend won't work, only hardcoding the file links in the source files help but even then the content of the target files doesn't show up on my site. Code in setup file is this one
```
plugin.tx_pxanewslettersubscription {
    view {
        templateRootPaths {
        0 = fileadmin/private/ext/pxa_newsletter_subscription/Templates/
    }

    partialRootPaths {
        0 = fileadmin/private/ext/pxa_newsletter_subscription/Partials/
    }

    layoutRootPaths {
        0 = fileadmin/private/ext/pxa_newsletter_subscription/Layouts/
    }
}
```

Any hints? :)

**Comment by PowerKiKi** [comment]
The statistics is entirely automated, the only thing you need to do is enable it there: 

![image](https://user-images.githubusercontent.com/72603/40460941-0619a044-5f44-11e8-81a4-24bbcdbb1759.png)

The two SQL fields you are talking about are entirely optional and for custom use only. Typically you would not select/update newsletter tables yourself. Read the doc for examples of what you could do with that: https://docs.typo3.org/typo3cms/extensions/newsletter/Configuration/Recipient_List_SQL_Examples.html

For the template thing, I unfortunately cannot help you much, as I am not familiar enough with TypoScript.

**Comment by Asfga** [comment]
Hm I always checked these fields when sending testmails but the statistic shows 0% at opened mails and 0% on clicked links, even if I open the mail on my test account and click on a link in it. Any idea why it doesn't recognize it?

**Comment by PowerKiKi** [comment]
What is the URL of the link you see in the received email ?

**Comment by Asfga** [comment]
For example link for unsubscription:
http://localhost/index.php?id=89&type=1342671779&tx_newsletter_p%5Baction%5D=unsubscribe&tx_newsletter_p%5Bcontroller%5D=Email&tx_newsletter_p%5Bc%5D=6e07e2b5a4ccc608fe76a6d57a541f3a

Other links just have a different hash at the end. If clicking any link, page not found appears (Reason: Request parameters could not be validated (&cHash empty)). The href for the link is e.g. href="http://www.twitter.com/" or the unsubscription url of the extension.

**Comment by PowerKiKi** [comment]
The cHash thing is only loosely related this extension. We never use them. Have a look at https://forum.typo3.org/index.php/t/215652/typo3-8-6-amp-chash-empty, or even better yet at https://docs.typo3.org/typo3cms/extensions/core/8.7/Changelog/8.5/Breaking-78002-EnforceCHashArgumentForExtbaseActions.html

And try something like:

```
plugin.tx_newsletter.features.requireCHashArgumentForActionArguments = 0
```

**Comment by Asfga** [comment]
Sorry for being inactive the last days...I looked a little bit closer to the links in the email template and every link is different. But if I send the newsletter and look at the links in the newsletter, every link is like the above. So something must transform all links for whatever reason..

**Comment by PowerKiKi** [comment]
Did you see, and try, my previous post ?

**Comment by PowerKiKi** [comment]
Can you give me the exact URL for:

1. the original URL as seen in the original HTML source from your browser (before Newsletter)
2. the URL found in the received email source when "detect clicked links" is checked
3. the URL found in the received email source when "detect clicked links" is **not** checked
4. the final URL you reach when the link is clicked when "detect clicked links" is checked
5. the final URL you reach when the link is clicked when "detect clicked links" is **not** checked
