### ISSUE TITLE
Task "Send Newsletter" gets stuck running as cronjob (TYPO3 8.7)

### ISSUE THREAD

**Issue by alexloetscher** [Ecodev/newsletter#161]
Hello

I've updated TYPO3 from 6.2 to 8.7 and the newsletter extension to 3.3.1. 
Everything works fine (thanks for your work), except the "send newsletter" task as cronjob. When I start the task manually it works fine.
As far as a can see, it stucks in the substituteMarkers() function in the mailer class. 
To be precise: In the getMarkers() function it gets stuck (https://github.com/Ecodev/newsletter/blob/2b575eff2d78147c7fed0a7c36f33b49522118ea/Classes/Utility/MarkerSubstitutor.php#L101). It can't get the recipientData?

I did set the $_SERVER['HTTP_HOST'] variable manually, but without any success.

Do you have any idea?

regards,
Alex

**Comment by PowerKiKi** [comment]
did you triple check that the PHP version and its configuration is absolutely identical when run from the web, manually from CLI and automatically via cron ?

**Comment by alexloetscher** [comment]
Thanks for the hint. The configuration is not absolutely identical. I have to check that with my hoster. 
I will inform you, after I know more.
