### ISSUE TITLE
[BUG] Embed images with special chars in url

### ISSUE THREAD

**Issue by rr-it** [Ecodev/newsletter#163]
The feature to embed images into the email does not work with image-urls containing special chars like "ä", "ö", "ü" etc.

`Ecodev.Newsletter.Mailer::findAttachments` searches the email-html-sourcecode for image-urls. The image-urls found are already urlencoded. Therfore the urls must be urldecoded before being processed further.

https://github.com/Ecodev/newsletter/blob/2b575eff2d78147c7fed0a7c36f33b49522118ea/Classes/Mailer.php#L186

As a fix I propose to change this line to:
`
                $swiftEmbeddedMarker = $this->getSwiftEmbeddedMarker(rawurldecode($url));
`

**Comment by PowerKiKi** [comment]
Your fix looks like it should work. Would you please create a PR and cover it with functional tests ?
