### ISSUE TITLE
Migrate away from Mcrypt

### ISSUE THREAD

**Issue by cyMarvin** [Ecodev/newsletter#165]
When saving a bounce account with PHP 7.2 you get the following error message:
![bildschirmfoto 2018-08-14 um 10 52 31](https://user-images.githubusercontent.com/26959854/44081901-31540bbc-9fb0-11e8-98f9-33c146992ca6.png)

The function mcrypt_create_iv used in Ecodev\Newsletter\Tools::encrypt($str) was removed.
Please see: http://php.net/manual/de/function.mcrypt-create-iv.php

Also mcrypt_encrypt will be removed soon.

**Comment by PowerKiKi** [comment]
This is unfortunately correct, we need to move from Mcrypt to something else (openssl?), maybe even nothing at all and go back to sorting plain passwords...

Any help on the matter would be very appreciated, I don't have availability in the foreseeable future.

**Comment by cyMarvin** [comment]
Please don’t save it plain. ^^
It seems to be only the encrypt and decrypt methods.
I’ll implement an openssl alternative with a PHP_VERSION check so it will be compatible with 7.2 and older versions.
Pull request coming soon. ;)
