### ISSUE TITLE
Support TYPO3 9 and drop all previous LTS

### ISSUE THREAD

**Issue by PowerKiKi** [Ecodev/newsletter#168]
Because of [increased complexity introduced by core](https://forge.typo3.org/issues/79025#note-21), we cannot reasonably support more than one LTS version at a time anymore. So we need to drop support for previous versions, including all hacks, and update tests against the new testing framework.

**Comment by PowerKiKi** [comment]
Re-evaluating the situation and it turns out that we use Newsletter only on TYPO3 7.6 (unfortunately). So we cannot reasonably drop support for that. We will continue to test automatically against TYPO3 7.6 until we migrate all our projects to a newer TYPO3 version. Only then will we upgrade our automated tests.

That means that, for now, TYPO3 8.7 and TYPO3 9.5 are tested manually and very sporadically.

**Comment by PowerKiKi** [comment]
So it turns out that supporting TYPO3 9 and anything older will be a huge pain. Notably because of https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Important-81023-DropTypo3db_legacy.html and https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.3/Deprecation-84965-VariousTypoScriptFrontendControllerMethods.html, and also probably because a ton of other non-identified things yet (eg: new routing system).

So, to support TYPO3 9 we must break support for all previous LTS, adapt to new test framework and thoroughly test the whole extension manually again. However, because of lack of resource and no interest int it for us, this won't happen anytime soon.

But if somebody has a need for it, I would accept a PR that implements all of that.

**Comment by fabarea** [comment]
I second that. I think this approach is reasonable.

**Comment by fabarea** [comment]
What about all the ExtJS part? Are we bound to it for ever? I know this is mainly a budget thing but asking if we could fade out this techno as well... Would be nice on the principle.

**Comment by PowerKiKi** [comment]
I'd love to get rid of it as I never liked working with it.

I'm also reluctant to introduce new dependencies, because of cost in maintenance work. But I don't think vanilla js would be viable. So I'm not really sure what to do... So I probably won't touch it unless it's really necessary...

**Comment by agiloweb** [comment]
My client is eagerly awaiting a TYPO3 9 version. So we are in the decision process of forking/PR/paying you.
Could you estimate the amount of work and a timeframe to get the TYPO3 9 version ready?
Would sponsoring be of help?

**Comment by PowerKiKi** [comment]
We are having an internal discussion about whether we should stop developing this extension entirely. Because moving to TYPO3 9 requires a lot of work and our own need for this extension is only shrinking...

A very rough estimate to migrate might be about 10 days of work, because ExtJS was dropped from TYPO3 core, the database layer changed entirely, the test framework is also completely breaking, and probably other things that we cannot foresee yet.

A decision was not reached yet, but for us it might be cheaper to move to mailchimp. Other alternatives might be to migrate to direct_mail or other similar extension...

Whatever happens, I'll be sure to let you know here what is going to happen (or not).

**Comment by fabarea** [comment]
I second what @PowerKiKi said. The topic is hot as we also have that need. We might come up with a light newsletter module which would be compatible with v9. We let you know as soon as we have something concrete.

**Comment by agiloweb** [comment]
Unfortunately direct_mail is not v9 ready either, and mailchimp in Germany is not easy with GDPR. So I hope you will have some positive news for me in the future ;-)

**Comment by fabarea** [comment]
Are you available / willing to be a beta tester?

**Comment by agiloweb** [comment]
Yes, sure

**Comment by grimmcreative** [comment]
Cant wait for TYPO3 9 Support 👯‍♂️ 
+1 for Beta Testing

**Comment by cdaecke** [comment]
I am available for testing as well :-)

**Comment by fabarea** [comment]
So here is the plan. We are currently abandoning this extension (EXT:newsletter) as such. This would simply require too much work to keep up to date. However, we are extending another extension of ours (EXT:messenger) which adds a newsletter module to send page content / free text as email as one would expect. One feature that we haven't restored though is the statistic feature. We saw it as not essential for a relaunch. 

Be noticed, the bread is still hot out of the oven and expect beta quality. I haven't tested yet in production. Only on my local for now. The plan is to put the extension production next week - as we need it - and I am planning to tag a version after that. In the meantime, don't hesitate to report on the project page https://github.com/fabarea/messenger

To install you would require EXT:vidi which powers the list module.

```
composer require fab/vidi
composer require fab/messenger dev-master
```

**Comment by fabarea** [comment]
BTW it is how it looks like:

![Screenshot](https://user-images.githubusercontent.com/620730/56240721-75d79600-6094-11e9-9996-5f47a4d50121.png)

Closing the issue here
