### ISSUE TITLE
implement feature for additional parameters in email-links (utm, etc.)

### ISSUE THREAD

**Issue by MoppieMop** [Ecodev/newsletter#40]
A feature for adding additional parameters to links in the email-content would be nice. In my case i need the following for tracking in Google Tag Manager: &utm_source=newsletter&utm_medium=email&utm_campaign=#uid#

I think the easiest way is to add a TS-setting in the function "getLinkAuthCode".

**Comment by PowerKiKi** [comment]
Closing for lack of feedback. Feel free to re-open with more information if need be.

**Comment by MoppieMop** [comment]
Oh, I was waiting for some feedback from you. 
Since there was no solution for me without changing the sourcecode i added some lines in `Mailer::getLinkAuthCode()`
```
if (strpos($url, 'newsletter_unsubscribe_url')===false) {
  if (strpos($url, '?') !== false) $url .= '&'; else $url .= '?';
  $url .= 'utm_source=newsletter&utm_medium=email&utm_campaign='. $this->newsletter->getUid();
}
```
This worked for me. But of course this is not the best solution.

**Comment by PowerKiKi** [comment]
Your seem pretty generic. Why would you say that it is not the best solution ? Because the behavior is not optional ?

What would make it better in your opinion ?
