### ISSUE TITLE
Test mail send two times and error messages

### ISSUE THREAD

**Issue by Oktopuce** [Ecodev/newsletter#43]
Hi,

When sending a newsletter in test mode, the newsletter is sent two times and I have an error message saying that there's a network connection problem and those error messages when trying to see the statistics :

````
An error occurred while trying to call Tx_Newsletter_Controller_NewsletterController->statisticsAction()
An error occurred while trying to call Tx_Newsletter_Controller_LinkController->listAction()
An error occurred while trying to call Tx_Newsletter_Controller_EmailController->listAction()
````

The statistics are not displayed the first time, I had to get out of the module and get in again in order to see the statistics.

Everythings works fine with the scheduler.

Regards,
Florian

**Comment by PowerKiKi** [comment]
Closing for lack of feedback. Feel free to re-open with more information if need be.
