### ISSUE TITLE
Implement feature to emergency-stop queued newsletters

### ISSUE THREAD

**Issue by stephankellermayr** [Ecodev/newsletter#46]
if someone queued a newsletter, there should be an option to stop the sending and delete the newsletter if something terrible goes wrong.
...or at least the possibility, to stop current sending and queue a new version for the rest of the recipients.

**Comment by marvin-martian** [comment]
I have thought about this too, I think a third main tab "Queues" would be nice.

((Thinking aloud))
Have a table:
```
Newsletter, Planned Time , Begin Time, Is Test, Status (waiting/processing/completed, #sent/#not-sent), Actions (Pause/Continue, Reschedule, Trash)
```

And of course the trash is more like:
```SQL
DELETE FROM `tx_newsletter_domain_model_email` WHERE `begin_time` = 0 AND `newsletter `= {tx_newsletter_domain_model_newsletter.uid};
```

Deleting completed newsletters should also be possible, but should come with a VERY BIG: Are you sure you want to do this? The reason for this is sometimes you may want to quickly clean up the test submissions.

**Comment by PowerKiKi** [comment]
Re-sending is a feature that was planned for a long time, see #3, but was never actually needed enough to be implemented.

I believe the "Queues" tab you are talking about is the Global statistics mentioned in #10. Meaning it is the same GUI as it exists today, except that it is accessible without selecting any pages and show all newsletter at once, including action (`cancel`, `delete`). I guess that would make sense.

**Comment by marvin-martian** [comment]
When you have a multi-user environment and some BE-users should only see statistics of some records and not others, and some users are allowed to manage newsletters and some not, it might be better to separate the management of queues away from the statistics. It is easier to disable a whole tab than various actions within the statistics. Statistics should be in the essence of the word, static. 

BTW an excel/csv export would be nice for stats. Marketing people love that sort of thing.

**Comment by PowerKiKi** [comment]
Closing because workarounds exist and it is not likely to be implemented in the foreseeable future (too much effort for very little gain).
