### ISSUE TITLE
unsubscribe-link in html-mail

### ISSUE THREAD

**Issue by MoppieMop** [Ecodev/newsletter#50]
In my template the i have `<a href="###newsletter_unsubscribe_url###">unsubscribe</a>`. The problem is, that this link is computed by the mail-open-spy-handler and so i get an invalid unsubscribe link with click-tracking.

**Comment by PowerKiKi** [comment]
Could you please provide the relevant HTML part of:

* original page as rendered by TYPO3
* page as previewed by Newsletter
* email actually received

**Comment by MoppieMop** [comment]
markup in Template:
`<a href="###newsletter_unsubscribe_url###">hier abbestellen</a>`
original page as rendered by TYPO3:
`<a href="index.php?id=189###newsletter_unsubscribe_url###">hier abbestellen</a>`
page as previewed by Newsletter
`<a href="http://www.domain.de/?tx_newsletter_p%5Baction%5D=clicked&amp;tx_newsletter_p%5Bcontroller%5D=Link&amp;type=1342671779&amp;url=http%3A%2F%2Fwww.domain.de%2Findex.php%3Fno_cache%3D1%26id%3D189%23%23%23newsletter_unsubscribe_url%23%23%23&amp;n=&amp;l=bfd3bfc4f691ecd1557669d8eb0bbbda">hier abbestellen</a>`
email actually received:
`<a href="http://www.ziffer-consulting.de/?tx_newsletter_p%5Baction%5D=clicked&amp;tx_newsletter_p%5Bcontroller%5D=Link&amp;type=1342671779&amp;url=http%3A%2F%2Fwww.ziffer-consulting.de%2F%2Findex.php%3Fno_cache%3D1%26id%3D189%23%23%23newsletter_unsubscribe_url%23%23%23&amp;n=75&amp;l=583704e0013e6b9c113a8a11c1e4f850" title="vom Newsletter abmelden">hier abbestellen</a>`

**Comment by PowerKiKi** [comment]
Use ``<a href="http://newsletter_unsubscribe_url">hier abbestellen</a>`` as explained there https://github.com/Ecodev/newsletter/blob/master/Documentation/Manual.rst#simple-substitutions

**Comment by MoppieMop** [comment]
Your solution works fine for me, but now I have a new problem on a differnet site. The site is only https but your suggested replacement only works for http://.
Can you please add https:// in your substituteMarker-function.

**Comment by PowerKiKi** [comment]
Please create a different issue.

**Comment by PowerKiKi** [comment]
@MoppieMop nevermind the ticket, I just released 2.5.1 with a fix for HTTPS.

**Comment by MoppieMop** [comment]
Big thanks! Not only for the fix. Especially for your good work on all the TYPO3 extensions and your fast replies.
