### ISSUE TITLE
On send testnewsletter -> the object type "Tx_Newsletter_Domain_Model_Newsletter" given to update must be persisted already, but is new

### ISSUE THREAD

**Issue by githubrsys** [Ecodev/newsletter#51]
the object type "Tx_Newsletter_Domain_Model_Newsletter" given to update must be persisted already, but is new occours after hitting the send testnewsletter button. Normal sending works as expected.

TYPO3 : 6.2.10-dev git 
Newsletter: git master from today

by examining the goog* I saw that this could be caused by the propertymapper but no clue what to do :-)

**Comment by PowerKiKi** [comment]
Can you give me the commit hash of your TYPO3 ? Did you see it working with
another TYPO3 version ?

**Comment by githubrsys** [comment]
The commit is from now -> 23a782ebc563dbe23c1661dc5866da2c9ad2ca64 . 
Just did the pull on 6_2 head. 

But I do not know when the error occoured first. But I bet it was with the switch to 6.2.10

**Comment by githubrsys** [comment]
PS: Don't forget to clear the reflection and opcode caches :-)

**Comment by PowerKiKi** [comment]
I can confirm that Newsletter is broken with TYPO3 older than 6.2.9. More specifically [this commit](https://review.typo3.org/gitweb?p=Packages%2FTYPO3.CMS.git;a=commit;h=15bde67f8271e9dd9cd917583d7f5f6d3b5dbe00) broke everything,

Since it affects a non-released version, I may **not** provide a patch depending on my availability. I may focus on namespacing everything and that may solve this particular bug if we are lucky. Meanwhile I strongly suggest you revert back to a stable version.

If it persists after 6.2.10 is released, please re-open. Or if you want to create a PR, I'll merge it.

**Comment by githubrsys** [comment]
I assume that a composer.json makes the world go round.
See this -> https://git.typo3.org/TYPO3CMS/Extensions/news.git/blob/991de43c29a333adfb7dbcdfeb11d558c5671a97:/composer.json

**Comment by PowerKiKi** [comment]
Maybe... but I didn't have time to document myself on the integration
between TYPO3 and composer. Would you have any link about that topic ?

I see duplication of features and data between composer.json and
ext_emconf.php. That's not very encouraging IMHO. And as much as I love
composer I would rather have a single system, rather than two overlapping
systems.

**Comment by githubrsys** [comment]
This is what I found -> http://composer.typo3.org/

**Comment by PowerKiKi** [comment]
@githubrsys if you are in development, you may want to try the brand new 'develop' branch. The code changed a lot, but nothing changed for end-user. If you have existing data, you will have to migrate them via Extension Manager "update" icon...

**Comment by githubrsys** [comment]
@PowerKiKi I'll give it a try as soon I have time left for that. Thank you in advance!

**Comment by PowerKiKi** [comment]
to be clear, I have no idea if it will work for you, but would gladly have
your feedback ;-)

**Comment by githubrsys** [comment]
Backend seems to work. Testsending worked also.  In FE there I have an error. But this could be caused of a non loaded TS setting. I'll later investigate time in.

``
Fatal error: Uncaught exception 'TYPO3\CMS\Extbase\Object\Container\Exception\UnknownObjectException' with message 'Could not analyse class:Ecodev\News\Controller\NewsController maybe not loaded or no autoloader?' in /var/www/web23/html/foo3/TYPO3.CMS1/typo3/sysext/extbase/Classes/Object/Container/ClassInfoFactory.php:37 Stack trace: #0 /var/www/web23/html/foo3/TYPO3.CMS1/typo3/sysext/extbase/Classes/Object/Container/Container.php(315): TYPO3\CMS\Extbase\Object\Container\ClassInfoFactory->buildClassInfoFromClassName('Ecodev\\News\\Con...') #1 /var/www/web23/html/foo3/TYPO3.CMS1/typo3/sysext/extbase/Classes/Object/Container/Container.php(157): TYPO3\CMS\Extbase\Object\Container\Container->getClassInfo('Ecodev\\News\\Con...') #2 /var/www/web23/html/foo3/TYPO3.CMS1/typo3/sysext/extbase/Classes/Object/Container/Container.php(108): TYPO3\CMS\Extbase\Object\Container\Container->getInstanceInternal('Ecodev\\News\\Con...', Array) #3 /var/www/web23/html/foo3/TYPO3.CMS1/typo3/sysext/extbase/Classes/Object/ObjectManager.php(94) in /var/www/web23/html/foo3/TYPO3.CMS1/typo3/sysext/extbase/Classes/Object/Container/ClassInfoFactory.php on line 37
`` 

BTW: If FE generates an error or a non found Template it would make sense to take this into account in the BE module while it looks like this:

![Image of BE](http://i.imgur.com/TRCXX5z.png)

**Comment by githubrsys** [comment]
Nope. FE completely broken with upper message.

What I did:

* pulled develop
* ran updatescript
* cleared all caches including reflection with installtool
* cleared opcodecache
* opened FE.

**Comment by githubrsys** [comment]
Removing ext:newsletter brings FE back

**Comment by PowerKiKi** [comment]
TYPO3 on 32626be46b4420de603ffa4ebcd08383ffa020a8
Newsletter on 3a73c6a8438060305a99457859e7b9eb10cfd2eb

Everything is working as expected, including sending test Newsletter, queuing Newsletter, previewing Email and actually sending via Scheduler. Also the "normal" pages of the website (I assume this is what you call "FE") are still working with or without Newsletter extension.

If you find a specific problem, please open a new issue.

**Comment by githubrsys** [comment]
I got the point. As soon ext:news and ext:newsletter is installed I get a weird namespace thing. If one of them is removed, everything is OK.

Has @georgringer an idea?

``
Fatal error: Uncaught exception 'TYPO3\CMS\Extbase\Object\Container\Exception\UnknownObjectException' with message 'Could not analyse class:Ecodev\News\Controller\NewsController maybe not loaded or no autoloader?' in /var/www/web23/html/TYPO3.CMS/typo3/sysext/extbase/Classes/Object/Container/ClassInfoFactory.php:37 Stack trace: #0 /var/www/web23/html/TYPO3.CMS/typo3/sysext/extbase/Classes/Object/Container/Container.php(315): TYPO3\CMS\Extbase\Object\Container\ClassInfoFactory->buildClassInfoFromClassName('Ecodev\\News\\Con...') #1 /var/www/web23/html/TYPO3.CMS/typo3/sysext/extbase/Classes/Object/Container/Container.php(157): TYPO3\CMS\Extbase\Object\Container\Container->getClassInfo('Ecodev\\News\\Con...') #2 /var/www/web23/html/TYPO3.CMS/typo3/sysext/extbase/Classes/Object/Container/Container.php(108): TYPO3\CMS\Extbase\Object\Container\Container->getInstanceInternal('Ecodev\\News\\Con...', Array) #3 /var/www/web23/html/TYPO3.CMS/typo3/sysext/extbase/Classes/Object/ObjectManager.php(94): TYP in /var/www/web23/html/TYPO3.CMS/typo3/sysext/extbase/Classes/Object/Container/ClassInfoFactory.php on line 37
``
## The Problem

Ecodev\News\Controller\NewsController 

I doubt that Newsletter has an NewController ... Perhaps it is a TYPO in any namespace declaration that leads to this?

**Comment by PowerKiKi** [comment]
It's unexpected but not entirely impossible. I use EXT:news as inspiration for some things...

Could you try with today 2.3.0 version please ?

Also, on a sidenote, it would be best to use 4 backtick ( ` ) when pasting multiline code/error, not only 2.

**Comment by githubrsys** [comment]
I did a git pull on develop before posting :-)

**Comment by PowerKiKi** [comment]
I expected so... could you please create a new ticket for this issue ? since it's entirely different from the original topic. Then I may have a look next week...
