### ISSUE TITLE
Unsubscribe link substitution fails if in href

### ISSUE THREAD

**Issue by githubrsys** [Ecodev/newsletter#56]
# Problem

if ###newsletter_unsubscribe_url### is placed within a href and "identify clicked links" is active the marker doesn't get substituted and looks like this.

````
http://domain/?tx_newsletter_p%5Baction%5D=clicked&tx_newsletter_p%5Bcontroller%5D=Link&type=1342671779&url=http%3A%2F%2Fdomain%2Fpage%3Ftype%3D9005%26L%3D%23%23%23newsletter_unsubscribe_url%23%23%23&n=706&l=5818b872d59258663c189f997e41a3a3
````

if you place ###newsletter_unsubscribe_url### in body and not as a href link the correct url is generated which is also functional. But it is no link at all.

**Comment by githubrsys** [comment]
but works as expected if unsubscribe link is set with fluid like this

``
<f:link.external uri="newsletter_unsubscribe_url">Unsubscribe</f:link.external>
``

**Comment by PowerKiKi** [comment]
Duplicate of #50. 

Use ``<a href="http://newsletter_unsubscribe_url">hier abbestellen</a>`` as explained there https://github.com/Ecodev/newsletter/blob/master/Documentation/Manual.rst#simple-substitutions
