### ISSUE TITLE
Problem with Attach images

### ISSUE THREAD

**Issue by ronnybaumann** [Ecodev/newsletter#57]
When you set "basic.attach_images" you will get an error while sending mails.
The error looks like this:
"Unable to open file for reading [url_to_image]"
This error comes from "Classes/Mailer.php" line 190.
The reason is "Swift_EmbeddedFile::fromPath($url)" expect a filesystem path but a url is given.

I could fix it like this:
Insert on line 187
$urlPath = str_replace($this->siteUrl, '', $url);
$urlPath = \TYPO3\CMS\Core\Utility\GeneralUtility::getFileAbsFileName($urlPath);

and then i changed:
$this->attachmentsEmbedded[$swiftEmbeddedMarker] = Swift_EmbeddedFile::fromPath($url);
to:
$this->attachmentsEmbedded[$swiftEmbeddedMarker] = Swift_EmbeddedFile::fromPath($urlPath);

TYPO3 6.2.10
Newsletter 2.3.2

**Comment by PowerKiKi** [comment]
Would you like to create a PR so that you get credited for this patch ? If you do so it would be best to cover the case with unit tests as well
