### ISSUE TITLE
Marker substitution in link + clicked links

### ISSUE THREAD

**Issue by siwa-pparzer** [Ecodev/newsletter#59]
If you use both a field substitution in a link and the feature "detect clicked links" following happens:

Link in the newsletter template:
``<a href="http://your-server/index.php?id=1&mail=###email###">unsubscribe newsletter</a>``

The plugin encodes the whole href part of the link and attaches its own functions for link detecting

Link in E-Mail
``http://your-server/index.php?id=1&tx_newsletter_p%5Baction%5D=clicked&tx_newsletter_p%5Bcontroller%5D=Link&type=1342671779&url=http%3A%2F%2Fyour-server%2Findex.php%3Fid%3D1%26mail%3D%23%23%23email%23%23%23&n=9&l=91a17808bc28c038e92b02257696becc``

so ``###email###`` is now ``%23%23%23email%23%23%23`` and therefore, the plugin doesn't inserts the E-Mail Address given by the recipient

**Comment by PowerKiKi** [comment]
As a workaround, to unsubscribe, you could use the built-in feature: ``<a href="http://newsletter_unsubscribe_url">unsubscribe newsletter</a>`` as explained there https://github.com/Ecodev/newsletter/blob/master/Documentation/Manual.rst#simple-substitutions

**Comment by siwa-pparzer** [comment]
Thanks - that should do it in the meantime

**Comment by PowerKiKi** [comment]
As [stated in code](https://github.com/Ecodev/newsletter/blob/master/Classes/Mailer.php#L416-L419), this might be unfixable:

We substitute markers last because we don't want to spy each links to view/unsubscribe (created via markers) for each recipient. Only the generic marker is enough. Otherwise we would mess up opened link statistics

**Comment by PowerKiKi** [comment]
You'll be happy to learn that I actually solved this issue, so your example should work as soon as I release next version.

**Comment by siwa-pparzer** [comment]
Great, thanks a lot.
I'm currently using the http:// syntax and it also works fine.
