### ISSUE TITLE
Update validation engine

### ISSUE THREAD

**Issue by PowerKiKi** [Ecodev/newsletter#6]
Update validation engine according to http://www.campaignmonitor.com/css/

Maybe refactor the engine in another class so the Newsletter class doesn't grow so much.

We need to consider using and optional premailer server instead of re-writing an entire validation engine: https://github.com/alexdunae/premailer

So we would have "simple" validation built-in, or advanced validation + fixing with a premailer server.

Also see, http://www.email-standards.org.

**Comment by marvin-martian** [comment]
My experience with the premailer ruby gem  is mixed. When it inlines css I still found myself going over the template by hand tweaking the css. It is also not magically dealing with Microsoft Office/Outlook fixes. Styling CSS for newsletter templates is still a black art, and there is still no magic button.
I do like the premailer plaintext conversions though. Very clean.

**Comment by marvin-martian** [comment]
When I think about it I don't think you should mess with the users newsletter templates. I had purposely a linked style sheet in the head that I knew may not get rendered in certain mail clients, but would be rendered in the browser. At the same time I added some styles in the body in some style tags. In its wisdom the newsletter extension assumed that I wanted my external style sheet added in the body as well. It did not see that I already had styles in the body. So it doubled up, which was undesirable.

The validation itself was throwing warnings but I knew I could ignore them as some css features I included with intent on targeting certain clients that would support the feature. In that sense the validation is not very useful. I think I would make validation as suggestions and not warnings.

I would also only make changes to the template on consent of the user. You can suggest fixes to the user, maybe show a fixed version, and ask them if they would like to send the "auto fixed" version or the original version. But maybe don't assume they want your changes.

**Comment by marvin-martian** [comment]
Just looking at the campaign monitor matrix it seems it would be possible to simulate to a certain degree the rendering of those mail clients in a modern browser. So you could produce a simulated preview by parsing the matrix and removing unsupported css. It would be an interesting project and a nice feature of the newsletter tool. Of course there are some features not marked in that matrix such as the 1790px high outlook 2007/11 page break on tables.

**Comment by marvin-martian** [comment]
Well I wrote the simulated preview lib: 
https://github.com/marvin-martian/HTMLMailClientRenderingSimulator 

It is not 100% but does do the Campaign Monitor guide 100%. To make it more comprehensive I would need a better test matrix. As a version 2 of the library I thought about coming up with a more comprehensive mail client test-matrix and crowd-source the testing of it in various mail clients and platforms. Maybe I can get some sponsorship for it.
