### ISSUE TITLE
BUG - deleted or hidden in tx_newsletter_domain_model_newsletter

### ISSUE THREAD

**Issue by siwa-pparzer** [Ecodev/newsletter#61]
If there are rows in table tx_newsletter_domain_model_newsletter where deleted=1 or hidden=1, then the scheduler throws an error.
Maybe the selection of all newsletters that should be sent, doesn't ask for these attributes.
If I delete all entries from tx_newsletter_domain_model_newsletter where deleted=1 or hidden=1, the scheduler sends as planned.

**Comment by PowerKiKi** [comment]
Could not reproduce on Newsletter 2.3.3 and TYPO3 6.2.10. 

I tried to schedule 4 newsletters, modify them to have all possible combinaison of ``deleted`` and ``hidden`` flags, then send all of them at once via the scheduler CLI command. Deleteted or hidden newsletters were correctly not sent, only the newsletter not deleted and not hidden were sent.

Please provide more details on your exact situtation and the error message seen.

**Comment by siwa-pparzer** [comment]
Error message:
[scheduler]: Task failed to execute successfully. Class: Ecodev\Newsletter\Task\SendEmails, UID: 5. PHP Catchable Fatal Error: Argument 1 passed to Ecodev\Newsletter\Tools::getConfiguredMailer() must be an instance of Ecodev\Newsletter\Domain\Model\Newsletter, null given, called in /websites/typo3/pwa/web2014/typo3conf/ext/newsletter/Classes/Tools.php on line 278 and defined in /websites/typo3/pwa/web2014/typo3conf/ext/newsletter/Classes/Tools.php line 85 (msg#4.0.1) 

Newsletter: 2.3.2

Typo3: 6.2.3

Additional Info:
The customer scheduled a newsletter and then deleted it, because he entered the wrong time.
Another possible error cause could be, that sites with sent newsletters were copied.

**Comment by PowerKiKi** [comment]
Is it something that is reproducible repetitively once it occurs ? or will it error once, and then work the next time ?

How is the scheduler run ? via the CLI command, or via the BE Scheduler module ?

What do you exactly mean by "sites with sent newsletters were copied" ? could you try to remove those copied records from DB and see if the errors still occurs ?

**Comment by siwa-pparzer** [comment]
yes, the error only disappears when the newsletter records are deleted from de database.

first i insert a line in the /etc/crontab and run it via BE Scheduler module

the client has multiple newsletter pages and copies one (so that he doesn't need to insert standard texts and images he uses very often)
Then he edits the text and wants to send this edited newsletter

For more accurate informations, how to reproduce the error i have to wait for my client - i think he wants to send one this week

**Comment by PowerKiKi** [comment]
I tried several time to reproduce but could not succeed. Once you know exactly what happens, maybe you could send me a DB dump of newsletter tables, or at least a very precise explanation on how to reproduce step-by-step.

**Comment by PowerKiKi** [comment]
Closing because of lack of feedback. Please re-open with new information if need be.

**Comment by siwa-pparzer** [comment]
The new version of the plugin fixes the problem.

**Comment by Oktopuce** [comment]
Same problem for me with cron/scheduler : 

PHP Catchable fatal error:  Argument 1 passed to Ecodev\Newsletter\Tools::getConfiguredMailer() must be an instance of Ecodev\Newsletter\Domain\Model\Newsletter, null given, called in /srv/http/www.xxxxxx.fr/public_html/typo3conf/ext/newsletter/Classes/Tools.php on line 210 and defined in /srv/http/www.xxxxxx.fr/public_html/typo3conf/ext/newsletter/Classes/Tools.php on line 67

The problem has been solved after executing this SQL Command :

`DELETE FROM `tx_newsletter_domain_model_newsletter` WHERE deleted=1 OR hidden=1`

--
Florian
