### ISSUE TITLE
Class TYPO3\CMS\Extbase\Mvc\Controller\FlashMessageContainer does not exist

### ISSUE THREAD

**Issue by al-Iskandar** [Ecodev/newsletter#62]
Installing newsletter in Typo3 v7.2 (with compatibility6) produces error message "Class TYPO3\CMS\Extbase\Mvc\Controller\FlashMessageContainer does not exist" in the backend

**Comment by PowerKiKi** [comment]
Newsletter 2.4.1 was [just released](https://github.com/Ecodev/newsletter/releases) and fix TYPO3 7.2 compatibility.
