### ISSUE TITLE
 function get() on a non-object -> Domain/Model/Link.php on line 135

### ISSUE THREAD

**Issue by githubrsys** [Ecodev/newsletter#64]
Occours if you upgrade core to 6.1.3-dev -> 027acbca6b7fdde07de9367aab64270a147b2e4d and you want to open the statistics

````
Fatal error: Call to a member function get() on a non-object in /var/www/vhosts/foo/typo3conf/ext/newsletter/Classes/Domain/Model/Link.php on line 135
````

Occoured in 2 Systems. One with latest git master version of newsletter. The other is a older newsletter installation dd1cf3b1f9fafd144ed114cc1edc140b1cdcd948.

I am not quite sure why that happens. Do you see a reason? -> https://git.typo3.org/Packages/TYPO3.CMS.git/shortlog

Cheers

**Comment by PowerKiKi** [comment]
I don't have any idea why this would break. I won't spend too much time supporting non-stable TYPO3, but if you are able to pin-point exactly since which commit of TYPO3 you see the error, then it will be much faster to fix, or at least understand it.

**Comment by githubrsys** [comment]
acknowledged. I'll recheck on stable when it's released.

**Comment by githubrsys** [comment]
can be closed. On 6.1.3 official release this behaviour was not reproduceable.
