### ISSUE TITLE
enhancement: move old db data to a kind of archive_table

### ISSUE THREAD

**Issue by githubrsys** [Ecodev/newsletter#65]
## Problem

If newsletter is in extensive usage, especially the tx_newsletter_domain_model_email table gets really big.  If you have some million records within the clickcount gets really slow.  Sure it's possible to truncate the table but then you would loose AFAIS any statistic data.

## Solution

I think it's a quite suitable solution to have a scheduler task which moves older records than a given period of time to a kind of archive table and if a request is done against records matching date older than given date, this table is taken into account four building the query instead of the tx_newsletter_domain_model_email table. 

This could also be true for tx_newsletter_domain_model_linkopenend and tx_newsletter_domain_model_link

what do you think . . . ?

**Comment by PowerKiKi** [comment]
Like you said, Newsletter was built to be able to truncate ``tx_newsletter_domain_model_linkopened`` while still preserving basic statistics. So it is a first "workaround" that should be used if table sizes becomes a problem.

However I am against making the system more complex ("archive" table) without first analyzing exactly the cause of the slowness you experienced. Our tests in https://github.com/Ecodev/newsletter/commit/425f5582713de912535d8434d9f78801a75ece87 already showed that 20'000 recipients were not slow. Also click registering were improved a lot recently (in b3334093ea797eb14f4fc08556b01a55dd005f26 and  cb161b9e0209b655fc2023608e0b23e4c71671a2)

What exactly was slow for you ? and could you provide us with an anonymized data dump of all newsletter tables in order to reproduce locally ?

**Comment by githubrsys** [comment]
I try to explain:

# facts

### tx_newsletter_domain_model_email
*	1,331,494 Rows
*   447 MiB

### tx_newsletter_domain_model_linkopenened
*	83,371 Rows
*   3,5 MiB	

### tx_newsletter_domain_model_link
*	5,142 Rows
*   0,5 MiB

### Newsletter reciepients
~ 9k

#### While a newsletter is sent / and ofc a lot of ppl. do open them at the same time

SELECT * FROM `tx_newsletter_domain_model_email` WHERE pid = 5315 ORDER BY `tx_newsletter_domain_model_email`.`open_time` ASC -> **Query took 45.0239 seconds**

-> Clickcount seems to have nearly that period of time

#### While a newsletter is not sent - but server still has some load

SELECT * FROM `tx_newsletter_domain_model_email` WHERE pid = 5315 ORDER BY `tx_newsletter_domain_model_email`.`uid` ASC -> **Query took 5.3979 seconds**

-> Clickcount seems to have nearly that period of time

#### While a newsletter is not sent - but server has not too much load
SELECT * FROM `tx_newsletter_domain_model_email` WHERE pid = 5315 ORDER BY `tx_newsletter_domain_model_email`.`uid` ASC -> **Query took 1.5263 seconds**

-> Clickcount seems to have nearly that period of time

#### Interestingly a plain
SELECT * FROM `tx_newsletter_domain_model_email` WHERE pid = 5315 -> **Query took 0.0008 seconds**

It's just a guess but it looks like that while a clickcount is running a select * runs against tx_newsletter_domain_model_email with any kind of matching in the background

**Comment by PowerKiKi** [comment]
Could you try the following SQL, and see if it helps ?
````ALTER TABLE `tx_newsletter_domain_model_email` ADD INDEX(`pid`);````

Also I am not sure what you call "Clickcount" ?

**Comment by githubrsys** [comment]
With clickcount I mean the action=clicked and perhaps action=opened which is enabled here.
The ADD INDEX(`pid`); does not gain the speed.

**Comment by githubrsys** [comment]
I think I found the Problem. The tx_newsletter_* Tables are type of myISAM in my Database for any reason. MyISAM does a Table based locking on joins. Solution is to change to innoDB because of row based locking. I'll change that tonight and see what happens.

**Comment by githubrsys** [comment]
Problem and solution confirmed. Changing to innoDB makes concurrent access to the tables fluent. Perhaps this should be added to the documentation. Therefore I leave this open until you decide to close it.

### While a newsletter is sent / and ofc a lot of ppl. do open them at the same time

``` SELECT * FROM `tx_newsletter_domain_model_email` WHERE pid = 5320 ORDER BY `tx_newsletter_domain_model_email`.`open_time` ASC -> Query took 0.0076 seconds ```

cheers

**Comment by PowerKiKi** [comment]
Thank for the investigation. By any chance would you be aware of a way in
TYPO3 to specify innodb ?

**Comment by githubrsys** [comment]
Sorry. I do not understand the sentence. :-)

**Comment by githubrsys** [comment]
See this -> https://git.typo3.org/Packages/TYPO3.CMS.git/blob/HEAD:/typo3/sysext/frontend/ext_tables.sql
