### ISSUE TITLE
Status page blank and connection error

### ISSUE THREAD

**Issue by kreilinger** [Ecodev/newsletter#66]
hey,

i just installed a fresh copy of typo3 6.2.13 and installed newsletter 2.4.1. No only additional plugins are tt_address and sr_email_subscribe.

no matter which page i click on using the newsletter module, the status page is always blank. ther is an ajax call that hangs and after some time i get the red "connection error message" from typo3. the ajax call is a post to http://domain.tld/typo3/mod.php?M=web_NewsletterTxNewsletterM1&moduleToken=b8785eef5bd76fe6380d2d1ad280b2dfb4b5efda&id=4&Ecodev\Newsletter\ExtDirectRequest=1

**Comment by PowerKiKi** [comment]
Can you find the exact error and stacktrace in apache log ? Or wherever you log errors ?

The URL doesn't give much info since important things are in the POSTed data.

**Comment by kreilinger** [comment]
the post data is:
[{"action":"NewsletterController","method":"listAction","data":null,"type":"rpc","tid":2},{"action":"BounceAccountController","method":"listAction","data":null,"type":"rpc","tid":3},{"action":"RecipientListController","method":"listAction","data":null,"type":"rpc","tid":4},{"action":"NewsletterController","method":"listPlannedAction","data":null,"type":"rpc","tid":5}]

only thing i can actually find in logs is the following:
cms: &no_cache=1 has been supplied, so caching is disabled! URL: "http://domain.tld/typo3/mod.php?M=web_NewsletterTxNewsletterM1&moduleToken=0353e33a183f815746db58d2ce02cebbd832b191&id=21&"

can you give mi a hint for getting more info?

**Comment by PowerKiKi** [comment]
Installing xdebug is always a good idea for development machine. Otherwise
you should at least enable development preset in TYPO3 install tools (you
should find a menu "preset" or similar which let you easily switch between
production and development settings).

**Comment by PowerKiKi** [comment]
Closing because of lack of feedback. Please re-open with new information if need be.
