### ISSUE TITLE
f:link.action section causes newsletter sending error

### ISSUE THREAD

**Issue by githubrsys** [Ecodev/newsletter#67]
### Summary

Today sending a newsletter via scheduler failed. The scheduler mentioned 'something went wrong' and did not send the newsletter. 

### The Cause
This was caused by an section in f:link.action
```
<f:link.action action="detail" pageUid="4605" arguments="{news:newsItem}" title="Webansicht zum Video" section="mainCol"> <f:cObject typoscriptObjectPath="lib.newsletterPLayImage" data="{xmediaElement.uid}" /></f:link.action>
```

### Solution
Once the section was removed the sending started instant. 

### Courious case
The Testnewsletter was sent without problem with the section attribute

**Comment by PowerKiKi** [comment]
This is probably not an issue directly with Newsletter, but rather the page itself.

According to what you described I'd bet that your page generate the same error if you try to access it via curl. To test tha scenario, re-add the part you removed, then open Newsletter module on that page. On the first tab of Newsletter module you ll see errors, warnings and info. You will find there the URL used by Newsletter to get the page. Try that URL via curl and debug whatever you find...

**Comment by githubrsys** [comment]
But the Testnewsletter is also generated with curl afaik. Nontheless I'll try your suggestion.

**Comment by PowerKiKi** [comment]
Also before re-running the scheduler, you should have a look in the database. Find the tx_scheduler_task table and find the last_error field (or something similar) for Newsletter. This field contains the serialized exception. Unfortunately it may be truncated and thus cannot be unserialized, however it is still very useful to read "manually" to understand what happened.

**Comment by PowerKiKi** [comment]
You are right about the fact that we always use curl and it should not make a difference between test/non-test....but better double check it

**Comment by githubrsys** [comment]
With a smaller recipient-List this could not be reproduced. I'll wait until next planned big sending to manually examine the db stored exception.

Cheers.

**Comment by PowerKiKi** [comment]
Closing for now. Please re-open if it happens again and you can get more info.
