### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by cosmox** [Ecodev/newsletter#70]
Version: TYPO3 6.2.14; Newsletter 2.5.1
If i start the sheduler task manuall, i got a PHP Fatal error:  

```
Call to a member function getRecipientData() on a non-object in /home/wf18001/www/typo3conf/ext/newsletter/Classes/Tools.php on line 220
```
Any ideas?

**Comment by cosmox** [comment]
Line 219: $email = $emailRepository->findByUid($emailUid);
Line 220: $recipientData = $email->getRecipientData();

**Comment by PowerKiKi** [comment]
> start the scheduler task manually

Is it via TYPO3 backend ? or via command line ?

Does it happen every time you run the scheduler ? or only once and then it works ?
Also what DB and PHP do you use ?

Could you dump `tx_newsletter_domain_model_*` tables and send them to me via email ? (you'll find my address in one of the commit message)

**Comment by PowerKiKi** [comment]
My guess is that something went wrong in `NewsletterRepository::findAllNewsletterAndEmailUidToSend()`, but have no idea what it could unless the data are somehow corrupted

**Comment by cosmox** [comment]
Hi powerKiKi,
here some more informations:
I get the error on everytime when i will executing the scheduler task in the TYPO3 Backend (by clicking the green icon)
This is the first time thar we want to send the NL by the Scheduler, we got no Problems on directly sending a Testmail.

MySQL Version 5.5.44-0+deb7u1-log
PHP 5.4.44-0+deb7u1

The Scheduler Task say: [It is configured to send 100 emails per execution. There is currently an approximative total of 2007 emails that needs to be sent for 0 planned newsletters and 3 newsletters being sent]

I will send you the Database dump via Mail

Thanks

**Comment by cosmox** [comment]
mm i didnt found your email address, can i use the contact address from the ext_emconf.php?

bye

**Comment by PowerKiKi** [comment]
you can use my github username at gmail.com. Also I won't be able to have a
look until, at best, next Friday, maybe later...

**Comment by cosmox** [comment]
Hi, okay i guess i found the reason for this behavior, i am truncate all db tables an create a new newsletter to send. Because i found different values inside the tx_newsletter_domain_model_newsletter table at col plain_converter
Old Entrys: Tx_Newsletter_Domain_Model_PlainConverter_Builtin
New Entrys: Ecodev\\Newsletter\\Domain\\Model\\PlainConverter\\Builtin

So i will test the Newsletter now once again

**Comment by cosmox** [comment]
okay i can confirmed that there are no more errors occured.
Maybe it is better to truncate the table on update but then we lost the statsitic

Seoul? I was in 2000 and 2001 in Korea and i am realy miss the food
best regards

**Comment by PowerKiKi** [comment]
Oh, you updated Newsletter from and older version ? then you definitely had to run the [update script](https://github.com/Ecodev/newsletter/blob/master/class.ext_update.php#L41) via the Extension Manager. That would have solved your issue. Anyway, glad you found a way out of that.

Yup, around Seoul. Don't know what I am gonna if I leave and can't have my 김치찌게 anymore :confused: ...
