### ISSUE TITLE
Compatibility issue with TYPO3 7.4 regarding property "script" in TCA of newsletter

### ISSUE THREAD

**Issue by dscoding** [Ecodev/newsletter#73]
Hi
The way registering a wizard in TCA has changed in 6.2 and was removed in CMS 7: https://docs.typo3.org/typo3cms/TCAReference/AdditionalFeatures/CoreWizardScripts/Index.html

Therefore, opening a newsletter element will result in an error. 

Replacing the the "script" property with module property as shown in docs should solve this.

Best.

**Comment by PowerKiKi** [comment]
Fixed by b8874543a61ff0dbf537ed2f120e8aef3c329f1e and released in 2.6.0
