### ISSUE TITLE
Compatibility issue with TYPO3 7.4 regarding call of enableExtJSQuickTips()

### ISSUE THREAD

**Issue by dscoding** [Ecodev/newsletter#74]
Hi
The call of the function enableExtJSQuickTips() in Classes/ViewHelpers/Be/ModuleContainerViewHelper.php will throw an error 500 in TYPO3 7.4

Migration is described here: https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/7.4/Breaking-68276-RemoveExtJSQuicktipsIfPossible.html

Best.

**Comment by PowerKiKi** [comment]
Fixed in release 2.6.0
