### ISSUE TITLE
Implement feature extConf basic variable overrides via TS

### ISSUE THREAD

**Issue by marvin-martian** [Ecodev/newsletter#75]
It would be nice to be able to override some extConf vars via template TS. i.e:
```
module.tx_newsletter.basic {
   sender_name = Tom & Jerry
   sender_email = t-j@cartoons.blah
   attach_images = 1
   keep_messages = 0
   append_url = &no_cache=1
   fetch_path =
   notification_email =
}
```
When you have a multidomain setup or you want to have multiple newsletters with different configs this would make life much easier for administration.

path_to_fetchmail, path_to_lynx, mails_per_round are very much dependent on the server set up so would not require an override

**Comment by marvin-martian** [comment]
I got this working pretty easily:

In Ecodev\Newsletter\Tools::confParam
```PHP
    /**
     * Get a newsletter-conf-template parameter
     *
     * @param    string   Parameter key
     * @return   mixed    Parameter value
     */
    public static function confParam($key)
    {
		// Look for a config in the module TS first.
		static $configTS;
		if (!is_array($configTS)) {
			$objectManager = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\\CMS\\Extbase\\Object\\ObjectManager');
			$beConfManager = $objectManager->get('TYPO3\\CMS\\Extbase\\Configuration\\BackendConfigurationManager');
			$configTS = $beConfManager->getTypoScriptSetup();
			$configTS = $configTS['module.']['tx_newsletter.']['config.'];
		}
		if (isset($configTS[$key])) {
			return $configTS[$key];
		}
		
		// Else fallback to the extension config.
        if (!is_array(self::$configuration)) {
            self::$configuration = unserialize($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['newsletter']);
        }

        return self::$configuration[$key];
    }
```

Basically any config in the newsletter extConf can now be overwritten via template TS.
```
module.tx_newsletter.config {
   sender_name = Tom & Jerry
   sender_email = t-j@cartoons.blah
   attach_images = 1
   keep_messages = 0
   append_url = &no_cache=1
   fetch_path =
   notification_email =
}
```

**Comment by PowerKiKi** [comment]
You might be surprised to learn that I don't believe in TS, so I won't invest any time in TS support. However if you submit a PR including documentation and tests, then I'll merge it.

On a side note, some of those configuration should be moved to the scheduler task, instead of global configuration (typically `mails_per_round`). But it doesn't really matter for this particular issue.

**Comment by marvin-martian** [comment]
> You might be surprised to learn that I don't believe in TS, so I won't invest any time in TS support. 

You might be surprised there are many aspects of Typo3 that I also do not like. Don't get me started! Firstly though I am in the business of getting stuff done and I try not to let ideals get in the way. :smile: 

However I am in a situation where I have a large multi-domain site with multiple BE users all with varying permissions and operating scopes. If you know of a way to configure a single install of the extension for complex configuration of varying uses without TS I am open to suggestion.

So far TS is doing the job so it is where I looked first.

>However if you submit a PR including documentation and tests, then I'll merge it.

Documentation I will supply, unit-tests not. I generally find unit-testing a waste of my time. I am not dissing unit-testing as an idea. It works well under certain circumstances, particularly when the person who writes the test does not write the code. But when the same person comes up with the test that they should pass, it is fruitless exercise as the assumptions of the test writer/coder are the one and the same. The tests do not enlighten the coder. It is just a waste of time. You will never know whether those assumptions have hand and foot because the coder is making the rules up as they go along. It doesn't make sense. 

So I do not write tests for my own code. I have written tests for others to pass. 
So you can accept my working functional code and benefit from it as that is all I have, (and considering it comes with good will and for nothing, that is a pretty good deal) or you can choose to ignore it, up to you.

I will patch my version to fix its problems and I will make this version publicly available. If you benefit out of that, fantastic, take what you want. But it will not stop my train if you don't, I need working functional software not ideals.

**Comment by PowerKiKi** [comment]
I believe unit tests are a key element in projects where the maintainer(s)/contributor(s) change overtime. Or if the development is sporadic. In those cases, tests play a very important role to avoid regressions.

But you are entirely free to have different opinion of course. I'm grateful for your contributions anyway and I will implement tests wherever I deem necessary.

**Comment by marvin-martian** [comment]
It is in the current pull-request #71
