### ISSUE TITLE
plainConverter value not being set from BE. Bug?

### ISSUE THREAD

**Issue by marvin-martian** [Ecodev/newsletter#76]
This seems like a JS bug, as the value of the plainConverter is not being set when the newsletter is submitted for sending. Tried it from both latest Chrome/Firefox. Could someone please double-check/confirm that this field value is not being set via the BE? Maybe it is just me. I did reinstall the extension.

Sample POST payload :
```
{"action":"NewsletterController","method":"createAction","data":[{"pid":"254","senderName":"Test Sender","senderEmail":"test@test.test","uidBounceAccount":1,"repetition":0,"injectOpenSpy":true,"injectLinksSpy":true,"uidRecipientList":7,"plannedTime":"2015-08-31T15:35:00+02:00","isTest":true}],"type":"rpc","tid":7}
```

Because the built-in plainConverter is fallback, it falls back to this value. I was just about to add another plainConverter, but i thought i would try out the lynx one first, only to find out that I could select it but the value was not being stored.

I am intending to eventually add support for premailer. ((https://github.com/premailer/premailer))
Premailer is a nice little ruby gem for doing preflight for HTML emails. It does nice plain text mails and can also do auto CSS inlining of styles.

**Comment by marvin-martian** [comment]
Ahh it seems that the value is being set when you reset the recipient list after changing the plain converter.  Hmm.... still not right though... this is very weird behavior in the BE.

**Comment by PowerKiKi** [comment]
Premailer integration would be awesome. It's a long overdue idea I had (see #6).

As for the bug I can reproduce it too in TYPO3 6.2. Have to have a closer look...
