### ISSUE TITLE
Broken links in email when using RealURL.

### ISSUE THREAD

**Issue by marvin-martian** [Ecodev/newsletter#77]
Because the type is just appended ( return self::$uriBuilder->buildFrontendUri() . "&type=1342671779" ) and not built through the extbase URIBuilder it breaks when using RealURL.

In Ecodev\Newsletter\Tools::buildFrontendUri you need to do something like this.
```
self::$uriBuilder
                ->reset()
                ->setUseCacheHash(false)
                ->setCreateAbsoluteUri(true)
                ->setArguments($arguments)
				->setTargetPageType(1342671779);

        return self::$uriBuilder->buildFrontendUri();
```

To get it working very cleanly with RealURL you need to also set the other REQUEST parameters through the extbase URIBuilder. As soon as I get time I will send a pull request with the fixes for this entire issue.

**Comment by PowerKiKi** [comment]
I believed you mentioned somewhere else that you completed the work and would submit a PR for that. I'll wait for your input, but if you can't make it for whatever reason, please let me know and I'll have a look.

**Comment by marvin-martian** [comment]
Yes please wait, I have the code, I just need to split it out as a separate PR as  RealURL also effects some BE calls the changes are spread. I have been a bit busy @work just need to find some quiet time to diff it out.

**Comment by marvin-martian** [comment]
It is in the current pull-request #71
