### ISSUE TITLE
Implement feature Reply-To in extConf

### ISSUE THREAD

**Issue by marvin-martian** [Ecodev/newsletter#78]
I was asked to have a separate Reply-To: added to the newsletter email header. It would be nice if this was configurable.

I will probably have a pull request for this when I integrate it in the near future if it is not done beforehand. Maybe I can combine it with issue #75

**Comment by PowerKiKi** [comment]
That sounds like a very reasonable use-case. What about storing this info at the newsletter level, instead of global extConf ?

**Comment by marvin-martian** [comment]
Yes, I haven't implemented this just yet but I will soonish. Just at the newsletter level is also ok with me. I think the Reply-To is more of an exception than the rule with mass mail sending.

**Comment by tazeverywhere** [comment]
+1
it would be very usefull, thx @marvin-martian @PowerKiKi

**Comment by marvin-martian** [comment]
It is in the current pull-request #71
