### ISSUE TITLE
View/Unsubscribe markers being overwritten by spylinks. 

### ISSUE THREAD

**Issue by marvin-martian** [Ecodev/newsletter#79]
I had a marker in the mail template:

```
<a href="http://newsletter_view_url" target="_blank">View in browser</a>
```

Because the spylinks were being processed before the markers being set, this marker was being overwritten by a spylink, and the view link was not being set.

To get around this in Mailer->injectLinksSpy add a check for view/unsubscribe markers in the urls and do not set them as spy links.
```
private function injectLinksSpy(Email $email, $isPreview)
    {
        /* Exchange all http:// links  html */
        preg_match_all('|<a [^>]*href="(https?://[^"]*)"|Ui', $this->html, $urls);
        foreach ($urls[1] as $i => $url) {
        	 if ( stripos($url,'newsletter_view_url') == false  && stripos($url,'newsletter_unsubscribe_url') == false ) {
        	
	            $newUrl = $this->getLinkAuthCode($email, $url, $isPreview);
	
	            /* Two step replace to be as precise as possible */
	            $link = str_replace($url, $newUrl, $urls[0][$i]);
	            $this->html = str_replace($urls[0][$i], $link, $this->html);
          }
        }
    }
```

**Comment by PowerKiKi** [comment]
Released in 2.5.2

**Comment by amDevDept** [comment]
Greetings,

you should implement this for the ### Markers as well.
Or update the dokumentation to ebtter reflect that these markers should not be used.
Thanks

**Comment by PowerKiKi** [comment]
@amDevDept could you please open a new issue to explain in more details what you want to do and what doesn't work for you ? this issue was solved, and I doubt the original description still applies to ### markers.
