### ISSUE TITLE
Implement feature to redirect to a website page on unsubscribe.

### ISSUE THREAD

**Issue by marvin-martian** [Ecodev/newsletter#81]
Instead of  (or alternative to) rendering a unsubscribe page after unsubscribing it would be nice to be able to set a redirection to another page within the website.

**Comment by PowerKiKi** [comment]
The unsubscribe page is built via fluid template and is overridable with your own template via TypoScript. This should give you quite a bit of freedom, even as a far as implementing a (dirty?) ViewHelper that would do the redirect you need. (or even worse a redirect client-side via HTML/JS)

**Comment by marvin-martian** [comment]
I have already implemented a configurable extbase redirect for this. Don't do anything just yet I will have a PR.

**Comment by marvin-martian** [comment]
It is in the current pull-request #71
