### ISSUE TITLE
Implement feature excel/csv export of newsletter statistics.

### ISSUE THREAD

**Issue by marvin-martian** [Ecodev/newsletter#82]
It would be nice to be able to get a excel/csv export of newsletter statistics. Marketers love statistics and love compiling reports of the *cough* success of their campaigns. :smile:

**Comment by PowerKiKi** [comment]
If someone create a PR for CSV (not Excel), I'd merge it, but I don't see an immediate need for that.

**Comment by marvin-martian** [comment]
I agree CSV is better, I don't have a need for this right now either I just thought about it. Eventually I know I will be asked for it though. So it can go on the back-burner.

**Comment by PowerKiKi** [comment]
This is not likely to be implemented anytime soon because of lack of interest. Closing for now.
