### ISSUE TITLE
Implement support for CE with usergroup access rights

### ISSUE THREAD

**Issue by MoppieMop** [Ecodev/newsletter#86]
It would be great if you can implement following: I make a page for a newsletter with muliple content-elements. Every CE has different access-rules (one CE for group "foo", one CE for group "bar", ...). 
Now if I send this page as newsletter the access-rules respect the assigned groups of my recipients. So depending on the groups of the recipient everyone gets another newsletter.

Similar but maybe not that difficult to implement: If you improve the marker ```###:IF: my_field ###<p>Bla bla bla</p>###:ENDIF:###``` so we can check for the groups of the user (fe_users). Now this only works if every user has only one group. If a user has more than one group they are seperated by comma.

**Comment by PowerKiKi** [comment]
I believe what you describe is already possible by using a SQL based recipient list. With custom SQL you can generate pretty much any field you may need that are then usable in marker syntax.

Also the newsletter content is retrieved via an HTTP GET. That means there is absolutely no way for the extension to impersonate a user . That would require a significant change of concept. Not that it would be bad, but it's very unlikely to happen in the forseeable future.

**Comment by MoppieMop** [comment]
Ok, good to know.
The solution with the marker is not the best (for the editor), but I am totally fine with that. You can address every single group. 
Maybe I will write a short wiki for this.
