### ISSUE TITLE
improve Html2Text-Converter

### ISSUE THREAD

**Issue by MoppieMop** [Ecodev/newsletter#88]
I dont know if you (PowerKiki) can do it (because of 3dparty), but it would be nice if there are some settings for the Html2Text-Converter.
First of all the generated linkList should be optional.

My second problem with the converter: there is only a trim before the html is converted to text, but I need a trim after the conversion. If there are some empty lines after the body-tag they are still there in the newsletter.
Maybe this should be configurable as well, because there could be some cases where the empty lines are required(?).

**Comment by MoppieMop** [comment]
Maybe there is another option: Is it possible to create my own PlainConverter for the correct triming and without the linklist. What is the best solution for this?

**Comment by PowerKiKi** [comment]
Have you tried filing issue/PR upstream at https://github.com/mtibben/html2text ?

Otherwise you are supposed to be able to add your own converter. In this case you could inherit/compose the existing version, and declare your version in config files.

It was meant to be doable, but i never heard of anybody doing it, so there may be some missing pieces...

**Comment by PowerKiKi** [comment]
I see that plainConverter options are hardcoded in https://github.com/Ecodev/newsletter/blob/master/Resources/Public/JavaScript/Planner/Planner.js. so you won't be able yo use the ExtJs interface to select your converter, but you could still use via list mode (given that you add your own config).

I'd accept a PR to make ExtJs options rely on https://github.com/Ecodev/newsletter/blob/master/Configuration/TCA/Newsletter.php. that would make a lot of sense...

**Comment by PowerKiKi** [comment]
Given the lack of feedback and the rather low usage/priority of plain text emails, I close this. If something new come up (such as a PR), feel free to re-open.
