### ISSUE TITLE
7.6 Fatal error

### ISSUE THREAD

**Issue by thombeck** [Ecodev/newsletter#89]
Hi, 
With TYPO3 7.6 I have this error when I click on the newsletter module : Fatal error: Class 'template' not found in typo3_src-7.6.0/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4493

I'm not a back end developer, I understand nothing about this...

Thanks in advance !

**Comment by PowerKiKi** [comment]
Thank you for taking time to report this bug. The culprit is most likely that line https://github.com/Ecodev/newsletter/blob/master/Classes/ViewHelpers/AbstractViewHelper.php#L87

I won't have time to fix right now, but should be able to do so next week. In the meantime if somebody else want to submit a PR for that, it would be welcome.

**Comment by thombeck** [comment]
Hi
I try to pushed but I have an error : permission to Ecodev/newsletter.git denied to thombeck. Maybe I made something wrong.
Here is the correction : \newsletter\Classes\ViewHelpers\AbstractViewHelper.php line 87 replace by

$GLOBALS['SOBE']->doc = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\CMS\Backend\Template\DocumentTemplate');

Next, there is another error with \Classes\ViewHelpers\Be\ModuleContainerViewHelper.php
The function enableExtJSQuickTips is not available anymore.

Thanks

**Comment by matthiaswe** [comment]
Hi,

same problem with my 7.6 installation as well.

i'm afraid that the fix needs to be more extensive. Just tried to disable "enableExtJSQuickTips" by changing "newsletter/Resources/Private/Templates/Module/Index.html" line 6  to:

<newsletter:Be.moduleContainer pageTitle="Newsletter" loadExtJs="true" loadExtJsTheme="true" enableExtJSQuickTips="false">

Error disappears but be-module is being rendered as empty frame. No further errors visible right now.

Right now i'm not worked deeply into typo3 development to provide a quick suggestion. If i figure out any new information i let you know.

Regards,
Matthias
![bildschirmfoto 2015-11-13 um 20 11 34](https://cloud.githubusercontent.com/assets/15837934/11154972/c64f3880-8a42-11e5-8f4f-35f7a57c364d.png)

**Comment by thombeck** [comment]
I made a pull request for the \newsletter\Classes\ViewHelpers\AbstractViewHelper.php
I have no idea to for the enableExtJSQuickTips bug for the moment

**Comment by farconada** [comment]
Same problem here, waiting for patch

**Comment by PowerKiKi** [comment]
Can't promise anything, but i am working on the 2.6.0 release nowadays. I
hope it comes out in a few days with those compatibility issues fixed.

**Comment by PowerKiKi** [comment]
It seems more complicated than I hoped. I restored the backend and things _should_ work, but it needs more testing. If any of you guys would like to help and try the `develop` branch (in a dev env) and report here, that would be very helpful.

**Comment by thombeck** [comment]
Hi
Nothing work for me with the devlop version.
There is no name and no picto in the module column.
If i click on the module and on a page I a blank view in the conten column.
No errors message who could help

**Comment by PowerKiKi** [comment]
Was it with latest commit db8298e28a812f64b5cac0c9488a3b60072d984f ? Anything specific on your install ? did you try to uninstall/install the extension (to get auto-updated) ?

**Comment by PowerKiKi** [comment]
I believe everything should be working with the brand new 2.6.0 release.

**Comment by matthiaswe** [comment]
Thank you very much for the quick fix!

I installed the new 2.6.0 release. There seems to be a little bug while loading the backend module "Web / Newsletter". If you configured your webpage in the page settings to explicitly use protocol http (tab behavior) und backend to be locked to ssl (install tool), the backend tries to redirect a part of your backend from https to http. My browser denies the redirect with a mixed content error (see attachment). Seems like the backend modules url shouldn't be generated with the frontend base url.

Workaround is pretty easy: set page settings to use protocol https or 'default' an backend is working fine.

Couldn't test the actual mail functions until now. If i find any other hint i'll let you know.

![bildschirmfoto 2015-12-01 um 21 25 54](https://cloud.githubusercontent.com/assets/15837934/11513240/5525d4be-9872-11e5-9381-1961cba59ae0.png)
