### ISSUE TITLE
Task "Send Newsletter" gets stuck running as cronjob (TYPO3 7.6)

### ISSUE THREAD

**Issue by matthiaswe** [Ecodev/newsletter#94]
Hi,

today i tried to configure the latest update with my TYPO3 7.6 installation. Everything is working so far, except the scheduled send-command. It seems like it's getting stuck in Tools::buildUriBuilder() on command "$GLOBALS['TSFE']->fetch_the_id();". The problem only occurs when running the task through cronjob. Invoking it via backend runs smooth without any errors. For debugging purposes i added a few logging commands and they stop immediately at "$GLOBALS['TSFE']->fetch_the_id();" and task is marked as "running" in backend forever.
Couldn't figure out how to fix this until now. Does this error occur on older TYPO3 Versions <7.6 and can you reproduce it with you installation, too?

regards,
Matthias

**Comment by matthiaswe** [comment]
Could find the problem. I followed the calls until the core-function fetch_the_id() at which the code got stuck:

/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php::fetch_the_id()
...
if ($this->page['url_scheme'] > 0) {
            $newUrl = '';
            $requestUrlScheme = parse_url(GeneralUtility::getIndpEnv('TYPO3_REQUEST_URL'), PHP_URL_SCHEME);
...
My page settings were configured on the welcome page (root) to protocol https. Because my Newsletter website linked to the start page (logo), fetch_the_id() figured out a mismatch between the newsletter source site (http) and the linked page (https). This resulted in calling a redirect:
...
HttpUtility::redirect($newUrl, $headerCode);
...
from which the calling code never returned.

My workaround was setting protocol on "default" for the startpage and this fixed the problem. Curiously running the task manually from backend didn't end up in this problem. I'm fine with this setting, however if there is another way to generate the url it might be more compatible for different usages.

**Comment by PowerKiKi** [comment]
Don't have acces to computer right now. But could you try something please ? When running via cron (more generally via CLI) we need to simulate a few things in order for routing to works. This can be seen in `Mailer` class near the line `$_SERVER['HTTP_HOST'] = $newsletter->getDomain();`. Coul you try to manually inject other variables that should be present if request was done bia SSL ? IIRC that would be something like "SSL" and/or "SSL_ON" ?

If that dirty workaround fix the problem, then we can think of a proper way to do that.

**Comment by Oktopuce** [comment]
Hi,

Same problem for me with Typo3 version 6.2 : it's stuck when running the task with cron.
But I don' use SSL and the code got stuck when calling $GLOBALS['TSFE']->getConfigArray(); in buildUriBuilder().

If I run the scheduled task manually it's ok.

Regards,
Florian

**Comment by PowerKiKi** [comment]
Try to upgrade to 2.6.1. Also is it a multi-domains install ?

**Comment by Oktopuce** [comment]
Thanks for your reply.
Yes it's a multi-domain.
Where can I find the 2.6.1 ?

**Comment by PowerKiKi** [comment]
It seems the auto release to TER did not happen. I'll have a look at that.

In the meantime this repository is always the source of truth. So you can always get latest release here. Eg: https://github.com/Ecodev/newsletter/releases/tag/2.6.1

**Comment by Oktopuce** [comment]
It's seems to be ok with the new release 2.6.1, no more stucks.
Thanks for your help.

**Comment by PowerKiKi** [comment]
Closing because lack of feedback from OP.

**Comment by PowerKiKi** [comment]
Actually this HTTPS thing should be better tested before closing...

**Comment by Oktopuce** [comment]
Hi, 
For me it seems to be ok (with Typo3 6.2).
It didn't stucks anymore since I've installed version 2.6.1.
During april/may, we will do some tests with large amount of data, I'll give you a feedback.
Thx,
Florian

**Comment by Oktopuce** [comment]
Ok I confirm that there's no problem anymore even with large amout of data.
