### ISSUE TITLE
Documentation: TS wrong element

### ISSUE THREAD

**Issue by kludikovsky** [Ecodev/newsletter#97]
![_screen_shot_2015-12-23_143035b](https://cloud.githubusercontent.com/assets/6077916/11977380/59e22b62-a982-11e5-8430-2fd886e44512.jpg)
There seems to be a smal error in the documentation describing the number of mails to send 8do to compy & paste). The element shows

config.**attach_images**	-  Number of mails to send per iteration.

config.attach_images - 	 is the same as in the item above.

I assume that should be something else.

**Comment by PowerKiKi** [comment]
Thanks for reporting. Fixed in https://github.com/Ecodev/newsletter/commit/6107018de9e8fb5af7b3f4fd1f8f4c7d42c967f8
