### ISSUE TITLE
Backend Editing- Receipient does not work

### ISSUE THREAD

**Issue by kludikovsky** [Ecodev/newsletter#98]
When editing the Receipient query there are several error in the backend.

1. After saving the title get lost in the field
![image](https://cloud.githubusercontent.com/assets/6077916/11979428/99859446-a993-11e5-8708-69ab4c570d1d.png)

2. When changing the type, basically nothing happens.
  * when selecting backend users, BE-users are shown, but non can be selected and included in the selection field. Any further action is inhibited
  * when selecting any FE types nothing is shown on the right side to select
3. The close (x) also does not work

**Comment by kludikovsky** [comment]
The following entry is raised in the error_log
```
[Thu Dec 24 11:03:24 2015] [error] [client 123.123.123.123] File does not exist: /var/www/vhosts/dom.tld/httpdocs/typo3/typo3, referer: http://dom.tld/typo3/index.php?route=%2Frecord%2Fedit&token=48128d00b8f742ce2237554adeb8bee6f23be0f5&edit[tx_newsletter_domain_model_recipientlist][4]=edit&returnUrl=%2Ftypo3%2Findex.php%3FM%3Dweb_list%26moduleToken%3Dd75516d486377b67537bab679ac2b96edffdc406%26id%3D59%26imagemode%3D1
[Thu Dec 24 11:03:24 2015] [error] [client 123.123.123.123] File does not exist: /var/www/vhosts/dom.tld/httpdocs/typo3/typo3, referer: http://dom.tld/typo3/index.php?route=%2Frecord%2Fedit&token=48128d00b8f742ce2237554adeb8bee6f23be0f5&edit[tx_newsletter_domain_model_recipientlist][4]=edit&returnUrl=%2Ftypo3%2Findex.php%3FM%3Dweb_list%26moduleToken%3Dd75516d486377b67537bab679ac2b96edffdc406%26id%3D59%26imagemode%3D1
```

There are two lines!

**Comment by PowerKiKi** [comment]
From your other posts I assume that you are running PHP 5.6, but what TYPO3 version ? 7.0 or 7.6 ?

**Comment by kludikovsky** [comment]
It's 
T3 - 7.6.1
PHP - 5.6.15
MySQL - 5.5.46

**Comment by vixe76** [comment]
Same error with T3 - 7.6.4 / PHP 7.0.3 ... I doesn't think that's is PHP related because I get a bunch of JS - Errors
![screenshot](https://cloud.githubusercontent.com/assets/2116790/14011876/3815cbac-f1a2-11e5-9d7d-671a2b981641.png)

**Comment by mch23** [comment]
When you edit recipients, the links to js core files are somehow wrong and that produce the js errors.
See network tab in developer tools. There is lot of 404 not found error because there is additional /typo3/ in path:

http://domain.com/typo3/typo3/sysext/core/Resources/Public/JavaScript/Contrib/require.js
http://domain.com/typo3/typo3/sysext/core/Resources/Public/JavaScript/Contrib/jquery/jquery-2.1.4.js
.. etc

**Comment by farconada** [comment]
same problem here, any news?

**Comment by mch23** [comment]
Downgrading typo3 to version 7.6.0 solves lot of issues.

**Comment by PowerKiKi** [comment]
Unfortunately no news to share about this. I am aware of the issue, but unfortunately won't have time for it until at least July.

If one of you could contribute a patch or even only an explanation of why  the URL is broken, that would be much appreciated.

**Comment by mch23** [comment]
Problem is that global typo3 paths are wrong after calling UriBuilder::buildFrontendUri(..) in Classes/Domain/Model/RecipientList.php on line 252,253. So I think it is problem in typo3 core.
Comment these two lines if you don't need export from recipeint list and then it works.

**Comment by farconada** [comment]
confirmed that comming works.

**Comment by PowerKiKi** [comment]
Mmh, building frontend URL from backend is a real PITA in TYPO3 if anybody has any advice about that topic that would be much appreciated. Right now, what we do is very hackish and is very likely to break things (like what we see here I guess), because we manipulate global variables.

**Comment by glucka** [comment]
Thanx @mch23! it works!!!
